// Keep the story brief; the community photographs carry the page.
export const aboutCopy = {
  en: {
    eyebrow: 'ABOUT ROUNDY',
    title: 'Meet people.\nFeel the difference.',
    photoCaption: 'Real conversations. One Cup English, Seoul.',
    conversationAlt: 'One Cup English participants talking around a table',
    momentsAlt: 'Desserts shared under cherry blossoms',
    storyTitle: 'It started with\na conversation.',
    storyBody: 'We might have passed each other on an app. We met in person, and stayed together.',
    storySignature: 'Kyle & Joey',
    communityTitle: 'One table.\nMore possibilities.',
    communityBody: 'From thoughtful discussions at One Cup English to new connections at Roundy.',
    proofValue: '80+',
    proofLabel: 'paid members to date',
    source: 'One Cup English',
    teamTitle: 'Your hosts.',
    kyle: 'Kyle',
    joey: 'Joey',
    role: 'Community Manager',
    kyleBackground: 'Software Engineer & Ex-Interpreter',
    joeyBackground: 'Product Manager',
    trustTitle: 'Feel at ease.',
    trust: ['Profiles reviewed', 'QR check-in', 'Contact details shared only after a mutual match', 'Private safety reports'],
    safety: 'How it works & safety',
    events: 'Find your next conversation',
  },
  ko: {
    eyebrow: '라운디 소개',
    title: '직접 만나면,\n달라지는 것들.',
    photoCaption: '영어 한잔에서 함께한 대화의 순간.',
    conversationAlt: '테이블에 둘러앉아 대화하는 영어 한잔 참가자들',
    momentsAlt: '벚꽃 아래에서 함께한 디저트',
    storyTitle: '우리도 대화로\n시작했어요.',
    storyBody: '앱에서는 스쳐 갔을지도 모를 두 사람. 직접 만나 대화했고, 지금도 함께하고 있어요.',
    storySignature: '카일과 조이',
    communityTitle: '같은 테이블,\n새로운 가능성.',
    communityBody: '시사로 깊어지는 영어 한잔의 대화에서, 라운디의 새로운 만남으로.',
    proofValue: '80+',
    proofLabel: '누적 유료 회원',
    source: '영어 한잔',
    teamTitle: '함께할 호스트.',
    kyle: '카일 Kyle',
    joey: '조이 Joey',
    role: '커뮤니티 매니저',
    kyleBackground: '소프트웨어 엔지니어 & 전직 통역사',
    joeyBackground: '프로덕트 매니저',
    trustTitle: '편안하게 만나요.',
    trust: ['참여 전 프로필 검토', 'QR 체크인', '서로 선택한 경우에만 연락처 공유', '비공개 안전 신고'],
    safety: '이용 방법 및 안전',
    events: '새로운 대화 만나러 가기',
  },
} as const;
