export const demoMode = !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
export const interests = ['Coffee','Running','Travel','Food','Film','Music','Hiking','Art','Books','Tech','Cooking','Design','Museums','Photography','Football','Yoga'];
export type Event = {id:string;slug:string;title:string;neighborhood:string;starts_at:string;ends_at:string;venue:string;address:string;age_min:number;age_max:number;capacity:number;seats_remaining:number;theme:string;description:string;image:string;status:string};
export const events: Event[] = [{id:'demo-yeouido',slug:'saturday-social',title:'Saturday Social',neighborhood:'Yeouido',starts_at:'2026-10-10T10:00:00Z',ends_at:'2026-10-10T12:00:00Z',venue:'Sample venue',address:'Yeouido, Seoul — illustrative event',age_min:26,age_max:35,capacity:12,seats_remaining:4,theme:'A Fresh Start',description:'A small room, a few new faces, and conversations that go somewhere. Spend an evening meeting people one at a time, entirely in English.',image:'/images/yeouido.webp',status:'published'},{id:'demo-anam',slug:'sunday-slow-dating',title:'Sunday Slow Dating',neighborhood:'Anam',starts_at:'2026-10-18T07:00:00Z',ends_at:'2026-10-18T09:00:00Z',venue:'Sample venue',address:'Anam, Seoul — illustrative event',age_min:24,age_max:33,capacity:12,seats_remaining:6,theme:'Take Your Time',description:'Make room for an unexpected connection. Thoughtful conversations, a welcoming host, and a Sunday afternoon well spent.',image:'/images/anam-korea-university.webp',status:'published'}];
export function dateLabel(value:string){return new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',month:'short',day:'numeric',weekday:'short'}).format(new Date(value));}
export function timeLabel(value:string){return new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',hour:'numeric',minute:'2-digit'}).format(new Date(value));}
export type Profile = {full_name:string;birth_date:string;gender:string;nationality:string;height_cm:number;job_title:string;workplace:string;public_job:string;public_workplace:string;phone:string;contact_consent:boolean;interests:string[];photos:string[]};
export const emptyProfile:Profile={full_name:'',birth_date:'',gender:'',nationality:'',height_cm:170,job_title:'',workplace:'',public_job:'',public_workplace:'',phone:'',contact_consent:false,interests:[],photos:[]};
export const sampleProfile:Profile={full_name:'Jamie Kim',birth_date:'1997-05-10',gender:'female',nationality:'Korean',height_cm:168,job_title:'Product designer',workplace:'Example studio',public_job:'Designer',public_workplace:'a creative company',phone:'+821000000000',contact_consent:true,interests:['Coffee','Art','Travel'],photos:['sample-avatar']};
export type Choice = 'no'|'maybe'|'yes';
export function profileComplete(p:Profile){return !!(p.full_name.trim()&&p.birth_date&&p.gender&&p.nationality.trim()&&p.height_cm>=100&&p.height_cm<=250&&p.job_title.trim()&&p.workplace.trim()&&p.phone.match(/^\+?[0-9\s-]{8,20}$/)&&p.contact_consent&&p.photos.length>=1&&p.photos.length<=3&&p.interests.length>=3&&p.interests.length<=10);}
