'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {tr,type Locale} from '@/lib/locale';
import {LoadingScreen} from './loading-screen';

type Report={id:string;user_id:string;context:string;reason:string;kind:string;status:string;created_at:string;report_reviews:{notes:string;updated_at:string}|null};
const statuses=[['new','New','신규'],['reviewing','Reviewing','검토 중'],['resolved','Resolved','처리 완료'],['dismissed','Dismissed','종결']] as const;
export function AdminReports({locale}:{locale:Locale}){
 const [rows,setRows]=useState<Report[]>([]),[total,setTotal]=useState(0),[status,setStatus]=useState('all'),[kind,setKind]=useState('all'),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/admin/reports?status=${status}&kind=${kind}&page=${page}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.reports);setTotal(d.total);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[status,kind,page,revision]);
 return <section className="admin-panel"><div className="admin-heading"><p className="admin-kicker">Roundy Admin</p><h1>{tr(locale,'Reports & feedback','신고 및 피드백')}</h1><p>{tr(locale,'Review member concerns and suggestions. Staff notes are visible only to administrators.','회원의 신고와 제안을 검토하세요. 내부 메모는 관리자에게만 표시됩니다.')}</p></div>
 <div className="reports-filters"><label>{tr(locale,'Status','상태')}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);setMessage('');}}><option value="all">{tr(locale,'All statuses','전체 상태')}</option>{statuses.map(([v,en,ko])=><option key={v} value={v}>{tr(locale,en,ko)}</option>)}</select></label><label>{tr(locale,'Type','유형')}<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0);setMessage('');}}><option value="all">{tr(locale,'All types','전체 유형')}</option><option value="report">{tr(locale,'Safety reports','안전 신고')}</option><option value="feedback">{tr(locale,'Feedback','피드백')}</option></select></label><button className="admin-secondary" onClick={()=>setRevision(v=>v+1)}>{tr(locale,'Refresh','새로고침')}</button></div>
 {message&&<p role="status">{message}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}
 {loading?<LoadingScreen/>:!error&&<><p>{tr(locale,`${total} submissions`,`${total}건 접수`)}</p><div className="reports-list">{rows.map(row=><ReportReview key={row.id+revision} row={row} locale={locale} onSave={()=>{setMessage(tr(locale,'Review saved. No message was sent to the member.','검토 내용을 저장했습니다. 회원에게 메시지는 전송되지 않았습니다.'));setRevision(v=>v+1);}}/>)}{!rows.length&&<p className="admin-empty">{tr(locale,'No submissions match these filters.','조건에 맞는 접수 내역이 없습니다.')}</p>}</div><div className="reports-pagination"><button className="admin-secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{tr(locale,'Previous','이전')}</button><span>{page+1} / {Math.max(1,Math.ceil(total/30))}</span><button className="admin-secondary" disabled={(page+1)*30>=total} onClick={()=>setPage(p=>p+1)}>{tr(locale,'Next','다음')}</button></div></>}
 </section>;
}
function ReportReview({row,locale,onSave}:{row:Report;locale:Locale;onSave:()=>void}){
 const [status,setStatus]=useState(row.status),[notes,setNotes]=useState(row.report_reviews?.notes??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="report-item"><summary><span><strong>{row.kind==='feedback'?tr(locale,'Feedback','피드백'):tr(locale,'Safety report','안전 신고')}</strong><span className="report-context">{row.context||tr(locale,'General','일반')}</span></span><span>{tr(locale,...(statuses.find(s=>s[0]===row.status)?.slice(1) as [string,string]??['New','신규']))}<small>{new Date(row.created_at).toLocaleString(locale==='ko'?'ko-KR':'en-GB',{timeZone:'Asia/Seoul'})} KST</small></span></summary><div className="report-body"><p className="report-text">{row.reason}</p><Link href={'/admin/members/'+row.user_id}>{tr(locale,'View reporting member','작성 회원 보기')}</Link><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/admin/reports/'+row.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,notes})});const result=await response.json();if(!response.ok)throw Error(result.error);onSave();}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}}>
 <label>{tr(locale,'Review status','검토 상태')}<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(([v,en,ko])=><option key={v} value={v}>{tr(locale,en,ko)}</option>)}</select></label><label>{tr(locale,'Private staff notes','관리자 전용 메모')}<textarea rows={4} maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={tr(locale,'Record investigation details and actions taken.','확인한 내용과 조치 사항을 기록하세요.')}/></label>{row.report_reviews&&<small>{tr(locale,'Last reviewed','최근 검토')}: {new Date(row.report_reviews.updated_at).toLocaleString(locale==='ko'?'ko-KR':'en-GB',{timeZone:'Asia/Seoul'})} KST</small>}{error&&<p role="alert" className="admin-error">{error}</p>}<button className="admin-primary" disabled={busy}>{busy?tr(locale,'Saving…','저장 중…'):tr(locale,'Save review','검토 저장')}</button></form></div></details>;
}
