'use client';
import { Heading } from '@/components/heading';
import { FormEvent,useEffect,useRef,useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { CalendarDays,ChevronLeft,Copy,Download,MapPin,Pencil,Play,Plus,Search,Share2,Trash2,Users,X } from 'lucide-react';
import { eventCategories,eventCategory,type Event } from '@/lib/data';
import { dateLabelForLocale,timeLabelForLocale,tr,ui,type Locale } from '@/lib/locale';
import type { Place } from '@/lib/naver';
import { uploadFile } from '@/lib/uploads';
import { LoadingScreen } from './loading-screen';
import { useToast } from './toast';
import { allNationalities, anyHeightRequirements, anySmokingRequirements, lockdownNotice, type HeightRequirements, type NationalityRequirements as Requirements, type SmokingRequirements } from '@/lib/event-requirements';
import { defaultParticipantDisclosures, eventLanguageLabel, participantDisclosureLabel, type EventLanguage, type ParticipantDisclosures } from '@/lib/event-presentation';
import { NationalityRequirements } from './nationality-requirements';
import { EventLifestyleRequirements } from './event-lifestyle-requirements';
import { OrderedImages } from './ordered-images';
import { AdminEventNight } from './admin-event-night';

type Form = {venue_description:string;nationality_requirements:Requirements;height_requirements:HeightRequirements;smoking_requirements:SmokingRequirements;participant_disclosures:ParticipantDisclosures;event_language:EventLanguage;gender_split_enabled:boolean;price_general:number;id?:string;title_en:string;title_ko:string;description_en:string;description_ko:string;category:string;date:string;time:string;venue:string;address:string;latitude:number|null;longitude:number|null;duration_minutes:number;capacity:number;age_min:number;age_max:number;lockdown_minutes:number;reminder_minutes:number|null;images:string[];status:string};
type Seating = {round:number;table:number;left:string;right:string}[];
const empty=():Form=>({venue_description:'',nationality_requirements:allNationalities(),height_requirements:anyHeightRequirements(),smoking_requirements:anySmokingRequirements(),participant_disclosures:defaultParticipantDisclosures(),event_language:'en',gender_split_enabled:true,price_general:0,title_en:'',title_ko:'',description_en:'',description_ko:'',category:'1:1 Speed Mingle',date:'',time:'19:00',venue:'',address:'',latitude:null,longitude:null,duration_minutes:120,capacity:16,age_min:25,age_max:35,lockdown_minutes:4320,reminder_minutes:null,images:[],status:'draft'});
const toForm=(e:Event):Form=>{const local=new Date(Date.parse(e.starts_at)+9*3600000).toISOString();return {venue_description:e.venue_description??'',nationality_requirements:e.nationality_requirements??allNationalities(),height_requirements:e.height_requirements??anyHeightRequirements(),smoking_requirements:e.smoking_requirements??anySmokingRequirements(),participant_disclosures:e.participant_disclosures??defaultParticipantDisclosures(),event_language:e.event_language??'either',gender_split_enabled:e.gender_split_enabled!==false,price_general:e.price_general??0,id:e.id,title_en:e.title,title_ko:e.title_ko??'',description_en:e.description,description_ko:e.description_ko??'',category:eventCategory(e),date:local.slice(0,10),time:local.slice(11,16),venue:e.venue,address:e.address,latitude:e.latitude??null,longitude:e.longitude??null,duration_minutes:e.duration_minutes??Math.round((Date.parse(e.ends_at)-Date.parse(e.starts_at))/60000),capacity:e.capacity,age_min:e.age_min,age_max:e.age_max,lockdown_minutes:e.lockdown_minutes??4320,reminder_minutes:e.reminder_minutes??null,images:e.images?.length?e.images:e.image?[e.image]:[],status:e.status==='draft'?'draft':'live'};};
async function request(path:string,init?:RequestInit){const r=await fetch('/api/'+path,{cache:'no-store',...init});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
function Offset({value,onChange,locale}:{value:number;onChange:(n:number)=>void;locale:Locale}){return <div className="offset-inputs"><label><span>{tr(locale,'Hours before','시간 전')}</span><input aria-label={tr(locale,'Hours before event','이벤트 전 시간')} type="number" min={0} max={720} value={Math.floor(value/60)} onChange={e=>onChange(Number(e.target.value)*60+value%60)}/></label><label><span>{tr(locale,'Minutes before','분 전')}</span><input aria-label={tr(locale,'Minutes before event','이벤트 전 분')} type="number" min={0} max={59} value={value%60} onChange={e=>onChange(Math.floor(value/60)*60+Number(e.target.value))}/></label></div>;}
function Modal({title,close,children,locale}:{title:string;close:()=>void;children:React.ReactNode;locale:Locale}){const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(close);closeRef.current=close;useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const root=ref.current;root?.querySelector<HTMLElement>('button,input')?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'&&root){const els=[...root.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href],select')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',onKey);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=overflow;previous?.focus();};},[]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="roundy-modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><header><Heading level={2}>{title}</Heading><button type="button" className="icon-button" aria-label={tr(locale,'Close','닫기')} onClick={close}><X/></button></header>{children}</div></div>;}
export function AdminEvents({locale,onEventsChanged,eventId,createNew=false}:{locale:Locale;onEventsChanged?:()=>void;eventId?:string;createNew?:boolean}){
 const router=useRouter();const params=useSearchParams();const duplicateId=createNew?params.get('duplicate'):null;const legacyEventId=params.get('event');const saving=useRef(false);
 const [eventQuery,setEventQuery]=useState('');const [statusFilter,setStatusFilter]=useState(params.get('status')==='draft'?'draft':'all');
 const {showToast}=useToast();
 const [events,setEvents]=useState<Event[]>([]),[form,setForm]=useState<Form|null>(createNew?empty():null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[places,setPlaces]=useState<Place[]>([]),[searchError,setSearchError]=useState('');
 const [seating,setSeating]=useState<{event:Event;rows:Seating;skipped:number;roster:{code:string;name:string}[]}|null>(null),[round,setRound]=useState(1);
 const [integrations,setIntegrations]=useState<{naver:boolean;reminders:boolean;summaries:boolean}|null>(null);
 const [nightEvent,setNightEvent]=useState<Event|null>(null);
 const [shareFile,setShareFile]=useState<File|null>(null),[shareUrl,setShareUrl]=useState('');
 async function load(){const d=await request('admin/events');setEvents(d.events||[]);return d.events as Event[];}
 useEffect(()=>{let active=true;setBusy(true);setError('');setForm(null);void Promise.all([request('admin/events').then(data=>{if(!active)return;const es=data.events as Event[];setEvents(es);const id=eventId||duplicateId||legacyEventId;if(id){const source=es.find(e=>e.id===id);if(!source)throw new Error('Event not found.');const draft=structuredClone(toForm(source));if(createNew){delete draft.id;draft.date='';draft.status='draft';}setForm(draft);}else if(createNew)setForm(empty());}),request('admin/integrations').then(data=>{if(active)setIntegrations(data);})]).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[eventId,createNew,duplicateId,legacyEventId]);
 useEffect(()=>()=>{if(shareUrl)URL.revokeObjectURL(shareUrl);},[shareUrl]);
 function update<K extends keyof Form>(key:K,value:Form[K]){setForm(f=>f?{...f,[key]:value}:f);}
 async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();if(!form||busy||saving.current)return;saving.current=true;const draft=structuredClone(form);await work(async()=>{const payload={...draft,starts_at:new Date(draft.date+'T'+draft.time+':00+09:00').toISOString()};const result=await request('admin/events'+(!createNew&&draft.id?'/'+draft.id:''),{method:!createNew&&draft.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();setForm(null);onEventsChanged?.();router.replace('/admin/events');showToast(tr(locale,'Event saved: /events/','이벤트가 저장되었어요: /events/')+result.event.slug,'success');});saving.current=false;}
 async function findPlaces(e:FormEvent){e.preventDefault();setBusy(true);setSearchError('');try{const d=await request('admin/places?q='+encodeURIComponent(query));setPlaces(d.places);if(!d.places.length)setSearchError(tr(locale,'No places found. Try a more specific name or address.','검색 결과가 없어요. 정확한 장소명이나 주소를 입력해 주세요.'));}catch(e){setSearchError(e instanceof Error?e.message:'Search failed');}finally{setBusy(false);}}
 async function generate(event:Event){await work(async()=>{const d=await request('admin/events/'+event.id+'/seating',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setSeating({event,rows:d.rows,skipped:d.skipped,roster:d.roster??[]});setRound(1);setShareFile(null);});}
 async function openSeating(event:Event){await work(async()=>{const d=await request('admin/events/'+event.id+'/seating');setSeating({event,rows:d.rows,skipped:d.skipped,roster:d.roster??[]});setRound(1);setShareFile(null);});}
 async function prepareImage(){if(!seating)return;await work(async()=>{await document.fonts.ready;const rows=seating.rows.filter(r=>r.round===round);const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=320+rows.length*90;const c=canvas.getContext('2d');if(!c)throw new Error('Image export unavailable');c.fillStyle='#fffefa';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#ff6666';c.fillRect(0,0,1080,18);c.fillStyle='#20211f';c.font='bold 50px "DM Sans", sans-serif';c.fillText('roundy',60,95);c.font='bold 32px "DM Sans", sans-serif';c.fillText(seating.event.title.slice(0,45),60,150);c.font='26px "DM Sans", sans-serif';c.fillText(`${dateLabelForLocale(seating.event.starts_at,locale)} — ${tr(locale,'Round','라운드')} ${round}`,60,202);rows.forEach((r,i)=>{const y=260+i*90;c.fillStyle=i%2?'#fff0f0':'#f3f3ee';c.fillRect(50,y-34,980,70);c.fillStyle='#20211f';c.fillText(`${tr(locale,'Table','테이블')} ${r.table}`,75,y+10);c.fillText(`${r.left}     ↔     ${r.right}`,460,y+10);});const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Export failed')),'image/png'));const file=new File([blob],`roundy-${seating.event.slug}-round-${round}.png`,{type:'image/png'});setShareFile(file);setShareUrl(URL.createObjectURL(blob));});}
 const filteredEvents=events.filter(event=>(statusFilter==='all'||event.status===statusFilter)&&[event.title,event.title_ko??'',event.venue].some(value=>value.toLowerCase().includes(eventQuery.toLowerCase())));
 const modal=search?<Modal locale={locale} title={tr(locale,'Search Naver Maps','네이버 지도 장소 검색')} close={()=>setSearch(false)}><form onSubmit={findPlaces} className="location-search-row"><input required value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr(locale,'Place name or street address','장소명 또는 도로명 주소')} aria-label={tr(locale,'Location search','장소 검색')}/><button className="admin-primary" disabled={busy}><Search size={18}/>{tr(locale,'Search','검색')}</button></form><div className="place-results">{places.map((p,i)=><button type="button" className="place-result" key={i} onClick={()=>{setForm(f=>f?{...f,venue:p.title,address:p.address,latitude:p.latitude,longitude:p.longitude}:f);setSearch(false);}}><strong>{p.title}</strong><span>{p.address}</span></button>)}</div>{searchError&&<p role="alert" className="admin-error">{searchError}</p>}</Modal>:null;
 return <section className="admin-panel">{busy&&<LoadingScreen/>}{error&&<p role="alert" className="admin-error">{ui(locale,error)}</p>}{eventId&&!form?<>{!busy&&<Link className="admin-back" href="/admin/events">{tr(locale,'All events','전체 이벤트')}</Link>}</>:form?<>
 <div className="admin-toolbar"><button className="admin-back" onClick={()=>router.push('/admin/events')}><ChevronLeft size={18}/>{tr(locale,'All Events','전체 이벤트')}</button><span className="admin-kicker">{tr(locale,form.id?'Edit Event':'Create New Event',form.id?'이벤트 수정':'새 이벤트 만들기')}</span></div>
 <div className="admin-heading"><Heading level={1}>{tr(locale,form.id?'Edit Event':'Create New Event',form.id?'이벤트 수정':'새 이벤트 만들기')}</Heading></div>
 <form className="admin-form" onSubmit={save}>
 <div className="admin-two localized-event-copy"><label><span>{tr(locale,'English Title','영문 제목')}</span><input required maxLength={120} lang="en" value={form.title_en} onChange={e=>update('title_en',e.target.value)}/></label><label><span>{tr(locale,'Korean Title','한글 제목')}</span><input required maxLength={120} lang="ko" value={form.title_ko} onChange={e=>update('title_ko',e.target.value)}/></label></div>
 <div className="admin-two localized-event-copy"><label><span>{tr(locale,'English Description','영문 설명')}</span><textarea aria-label={tr(locale,'English Description','영문 설명')} required maxLength={3000} rows={5} lang="en" value={form.description_en} onChange={e=>update('description_en',e.target.value)}/></label><label><span>{tr(locale,'Korean Description','한글 설명')}</span><textarea aria-label={tr(locale,'Korean Description','한글 설명')} required maxLength={3000} rows={5} lang="ko" value={form.description_ko} onChange={e=>update('description_ko',e.target.value)}/></label></div>
 <label><span>{tr(locale,'Category','카테고리')}</span><select value={form.category} onChange={e=>setForm(f=>f?{...f,category:e.target.value,gender_split_enabled:e.target.value==='Language Exchange'?false:f.gender_split_enabled}:f)}>{!eventCategories.some(category=>category===form?.category)&&<option value={form.category} disabled>{tr(locale,'Archived event','보관된 모임')}</option>}{eventCategories.map(category=><option key={category} value={category}>{category==='Language Exchange'?tr(locale,'Language Exchange','언어교환'):tr(locale,'1:1 Mingle','1:1 밍글')}</option>)}</select></label>
 <fieldset className="participant-disclosure-admin">
  <legend>{tr(locale,'Participant grouping and pricing','참가자 구분과 참가비')}</legend>
  <label className="check-row"><input type="checkbox" checked={form.gender_split_enabled} onChange={e=>update('gender_split_enabled',e.target.checked)}/><span>{tr(locale,'Separate attendees into Ladies and Gents','여성과 남성을 별도 그룹으로 구분')}</span></label>
  <p className="admin-help">{form.gender_split_enabled?tr(locale,'Existing format: half the seats per gender, separate pricing and gender-balanced rotations.','기존 방식: 성별별 정원과 참가비를 적용하고 남녀 교차 로테이션을 운영합니다.'):tr(locale,'Gender-neutral format: one shared capacity, one ticket price and all-gender pair rotations. Gender-specific eligibility requirements and gender-balance promotions are disabled.','성별 구분 없음: 하나의 통합 정원과 참가비를 적용하고 모든 참가자를 대상으로 로테이션합니다. 성별에 따른 참가 자격 제한과 성비 할인은 적용되지 않습니다.')}</p>
  {!form.gender_split_enabled&&<label><span>{tr(locale,'Ticket price per participant (KRW)','1인 참가비 (원)')}</span><input aria-label={tr(locale,'Ticket price per participant (KRW)','1인 참가비 (원)')} type="number" min={form.status==='live'?1000:0} max={10000000} step={1000} required value={form.price_general} onChange={e=>update('price_general',Number(e.target.value))}/><small className="admin-help">{tr(locale,'Set the actual participant fee before publishing. No booking can open with an unset price.','공개 전 실제 참가비를 입력하세요. 참가비가 정해지지 않은 행사는 공개할 수 없습니다.')}</small></label>}
 </fieldset>
 <label><span>{tr(locale,'Meetup Language','모임 진행 언어')}</span><select value={form.event_language} onChange={e=>update('event_language',e.target.value as EventLanguage)}><option value="en">{eventLanguageLabel('en',locale)}</option><option value="ko">{eventLanguageLabel('ko',locale)}</option><option value="either">{eventLanguageLabel('either',locale)}</option></select><small className="admin-help">{tr(locale,'This appears on the event page and tells participants which language the hosted rotations use.','이벤트 상세에 표시되며 로테이션 대화가 어떤 언어로 진행되는지 안내합니다.')}</small></label>
 <div className="admin-two"><label><span>{tr(locale,'Event Date','이벤트 날짜')}</span><input required type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label><span>{tr(locale,'Event Time (KST)','이벤트 시간 (한국 시간)')}</span><input required type="time" value={form.time} onChange={e=>update('time',e.target.value)}/></label></div>
 <p className="admin-help">{tr(locale,'Automatic URL','자동 URL')}: /events/{form.date?form.date.slice(5)+'-'+form.date.slice(0,4):'MM-DD-YYYY'} {tr(locale,'(same-day events receive a number)','(같은 날짜의 이벤트에는 번호가 붙어요)')}</p>
 <label><span>{tr(locale,'Location','장소')}</span><div className="location-search-row"><input required maxLength={160} value={form.venue} onChange={e=>{update('venue',e.target.value);update('latitude',null);update('longitude',null);}} placeholder={tr(locale,'Place name / location description','장소명 / 장소 설명')}/><button type="button" className="admin-secondary" onClick={()=>{setQuery(form.venue||form.address);setPlaces([]);setSearchError('');setSearch(true);}}><Search size={18}/>{tr(locale,'Search','검색')}</button></div></label>
 <label><span>{tr(locale,'Address','주소')}</span><input value={form.address} onChange={e=>{update('address',e.target.value);update('latitude',null);update('longitude',null);}} placeholder={tr(locale,'Filled automatically after selection','장소 선택 시 자동 입력')}/></label>
 <label><span>{tr(locale,'Additional venue description (optional)','장소 추가 설명 (선택)')}</span><textarea aria-label={tr(locale,'Additional venue description (optional)','장소 추가 설명 (선택)')} rows={3} maxLength={1000} value={form.venue_description} onChange={e=>update('venue_description',e.target.value)} placeholder={tr(locale,'e.g. Second floor, private room. Enter through the side door.','예: 2층 단독 공간입니다. 건물 옆문으로 들어오세요.')}/></label>
 <p className="admin-help">{tr(locale,'Search to fill coordinates automatically, or we will resolve the location name/address when you save.','검색하면 좌표가 자동 입력돼요. 직접 입력한 장소명이나 주소는 저장할 때 좌표를 확인해요.')}</p>
 {form.latitude!==null&&<div className="place-preview"><MapPin size={16}/> {form.address}<br/>{tr(locale,'Latitude / Longitude','위도 / 경도')}: {form.latitude}, {form.longitude}</div>}
 <div className="admin-two"><label><span>{tr(locale,'Duration (minutes)','진행 시간 (분)')}</span><input type="number" required min={15} max={1440} value={form.duration_minutes} onChange={e=>update('duration_minutes',Number(e.target.value))}/></label><label><span>{tr(locale,'Max Participants','최대 참가자 수')}</span><input type="number" required min={2} max={100} step={1} value={form.capacity} onChange={e=>update('capacity',Number(e.target.value))}/></label></div>
 <div className="admin-two"><label><span>{tr(locale,'Minimum Age','최소 연령')}</span><input type="number" required min={18} max={100} value={form.age_min} onChange={e=>update('age_min',Number(e.target.value))}/></label><label><span>{tr(locale,'Maximum Age','최대 연령')}</span><input type="number" required min={form.age_min} max={100} value={form.age_max} onChange={e=>update('age_max',Number(e.target.value))}/></label></div>
 {form.gender_split_enabled&&<NationalityRequirements value={form.nationality_requirements} onChange={value=>update('nationality_requirements',value)} locale={locale}/>} 
 {form.gender_split_enabled&&<EventLifestyleRequirements height={form.height_requirements} smoking={form.smoking_requirements} onHeightChange={value=>update('height_requirements',value)} onSmokingChange={value=>update('smoking_requirements',value)} locale={locale}/>}
 <fieldset className="participant-disclosure-admin"><legend>{tr(locale,'Participants Section Disclosure','참가자 섹션 공개 정보')}</legend><p className="admin-help">{tr(locale,'Choose which privacy-safe profile details appear publicly for confirmed participants in this event.','이 이벤트의 확정 참가자에게 공개할 개인정보 보호형 프로필 항목을 선택하세요.')}</p><div className="participant-disclosure-options">{(Object.keys(form.participant_disclosures) as (keyof ParticipantDisclosures)[]).map(key=><label className="check-row" key={key}><input type="checkbox" checked={form.participant_disclosures[key]} onChange={e=>update('participant_disclosures',{...form.participant_disclosures,[key]:e.target.checked})}/><span>{participantDisclosureLabel(key,locale)}</span></label>)}</div></fieldset>
 <fieldset><legend>{tr(locale,'Cancellation lockdown','이벤트 취소 제한')}</legend><Offset value={form.lockdown_minutes} onChange={n=>update('lockdown_minutes',n)} locale={locale}/><p className="admin-help">{lockdownNotice(form.lockdown_minutes,locale)}</p></fieldset>
 <fieldset><legend>{tr(locale,'Event Images','이벤트 이미지')}</legend><label className="document-upload"><strong>{tr(locale,'Upload event images','이벤트 이미지 업로드')}</strong><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||form.images.length>=10} onChange={e=>{const files=[...(e.target.files||[])];e.target.value='';if(!files.length)return;void work(async()=>{if(files.length+form.images.length>10)throw new Error(tr(locale,'Choose up to 10 images.','이미지는 최대 10개까지 선택할 수 있어요.'));const urls:string[]=[];try{for(const file of files)urls.push(await uploadFile(file,'wis-event-images'));}finally{if(urls.length)setForm(f=>f?{...f,images:[...f.images,...urls]}:f);}});}}/><small>📸 {tr(locale,'JPEG, PNG or WebP · Max 5 MB each · Up to 10 images','JPEG, PNG, WebP · 장당 최대 5 MB · 최대 10장')}</small></label><OrderedImages images={form.images} onChange={images=>update('images',images)} locale={locale} disabled={busy}/></fieldset>
 <fieldset><legend>{tr(locale,'Send Reminder via Kakao','카카오 알림 보내기')}</legend><label className="check-row"><input type="checkbox" checked={form.reminder_minutes!==null} onChange={e=>update('reminder_minutes',e.target.checked?1440:null)}/><span>{tr(locale,'Send a reminder before this event','이벤트 시작 전 알림 보내기')}</span></label>{form.reminder_minutes!==null&&<Offset value={form.reminder_minutes} onChange={n=>update('reminder_minutes',n)} locale={locale}/>} {form.reminder_minutes!==null&&!integrations?.reminders&&<p className="admin-integration-note">{tr(locale,'Kakao delivery is not connected yet. This timing will be saved, but reminders cannot be sent until the messaging provider is configured.','카카오 발송 서비스가 아직 연결되지 않았어요. 시간을 저장할 수 있지만 발송 서비스 연결 전에는 알림이 전송되지 않아요.')}</p>}</fieldset>
 <label><span>{tr(locale,'Status','상태')}</span><select aria-label={tr(locale,'Status','상태')} value={form.status} onChange={e=>update('status',e.target.value)}>{[['draft','Draft','초안'],['live','Published','공개']].map(([v,en,ko])=><option key={v} value={v}>{tr(locale,en,ko)}</option>)}</select><small className="admin-help">{tr(locale,'Draft events are hidden. Published events appear publicly. Applications close when the event starts or fills up.','초안은 공개되지 않아요. 공개 이벤트는 시작 시간이 지나거나 정원이 차기 전까지 공개돼요.')}</small></label>
 <div className="admin-form-actions"><button type="button" className="admin-secondary" onClick={()=>router.push('/admin/events')}>{tr(locale,'Cancel','취소')}</button><button className="admin-primary" disabled={busy} type="submit">{tr(locale,'Save Event','이벤트 저장')}</button></div></form></>:<>
 <div className="admin-toolbar"><span className="admin-kicker">Roundy Admin</span><button className="admin-add" onClick={()=>router.push('/admin/events/new')}><Plus size={18}/>{tr(locale,'Create New Event','새 이벤트 만들기')}</button></div><div className="admin-heading"><Heading level={1}>{tr(locale,'Events','이벤트')}</Heading></div>
 <div className="admin-filters"><label><span>{tr(locale,'Search events','이벤트 검색')}</span><input value={eventQuery} onChange={e=>setEventQuery(e.target.value)} placeholder={tr(locale,'Title or venue','제목 또는 장소')}/></label><label><span>{tr(locale,'Status','상태')}</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">{tr(locale,'All statuses','전체 상태')}</option><option value="draft">{tr(locale,'Draft','초안')}</option><option value="live">{tr(locale,'Published','공개')}</option></select></label></div>
 {!filteredEvents.length&&!busy?<div className="admin-empty"><CalendarDays size={28}/><p>{tr(locale,'No events match this view.','표시할 이벤트가 없어요.')}</p></div>:<div className="admin-event-list">{filteredEvents.map(event=><article className="admin-event" key={event.id}><Link className="admin-event-detail-link" href={'/events/'+event.slug} aria-label={tr(locale,'View event: ','이벤트 보기: ')+event.title}/><div className="admin-event-meta"><span className={'admin-status '+(event.status==='draft'?'draft':'live')}>{tr(locale,event.status==='draft'?'Draft':'Published',event.status==='draft'?'초안':'공개')}</span><span>{event.seats_remaining}/{event.capacity} {tr(locale,'places left','자리 남음')}</span></div><Heading level={2}>{event.title}</Heading><p><CalendarDays size={16}/>{dateLabelForLocale(event.starts_at,locale)} / {timeLabelForLocale(event.starts_at,locale)} KST</p><p><MapPin size={16}/>{event.venue}</p><div className="admin-event-actions"><button onClick={()=>router.push('/admin/events/'+event.id)}><Pencil size={16}/>{tr(locale,'Edit Event','이벤트 수정')}</button><button onClick={()=>router.push('/admin/events/new?duplicate='+event.id)}><Copy size={16}/>{tr(locale,'Duplicate Event','이벤트 복제')}</button>{eventCategory(event)!=='Archived event'&&<button className="admin-night-button" onClick={()=>setNightEvent(event)}><Play size={16}/>{tr(locale,'Run Meetup','밋업 진행')}</button>}<button onClick={()=>void generate(event)}><Users size={16}/>{tr(locale,'Generate Seating','좌석 배치 생성')}</button><button onClick={()=>void openSeating(event)}><Share2 size={16}/>{tr(locale,'Share Seating Image','좌석 배치 이미지 공유')}</button><button className="admin-delete" aria-label={tr(locale,'Delete event','이벤트 삭제')} onClick={()=>{if(window.confirm(tr(locale,'Delete this event from listings? Booking history is kept. Tickets for an upcoming event are returned.','이 이벤트를 목록에서 삭제할까요? 예약 기록은 보관되며, 시작 전 이벤트의 티켓은 반환됩니다.')))void work(async()=>{await request('admin/events/'+event.id,{method:'DELETE'});await load();onEventsChanged?.();});}}><Trash2 size={16}/></button></div></article>)}</div>}</>}
 {modal}{nightEvent&&<Modal locale={locale} title={tr(locale,'Meetup Control','밋업 컨트롤')} close={()=>setNightEvent(null)}><AdminEventNight event={nightEvent} locale={locale}/></Modal>}{seating&&<Modal locale={locale} title={tr(locale,'Seating Plan','좌석 배치')} close={()=>{setSeating(null);setShareFile(null);}}><p>{seating.event.title}</p>{seating.skipped>0&&<p className="note">{tr(locale,`${seating.skipped} excluded pairings are rest breaks.`,`${seating.skipped}개의 제외된 대화는 휴식 시간이에요.`)}</p>}<label>{tr(locale,'Round','라운드')} <select value={round} onChange={e=>{setRound(Number(e.target.value));setShareFile(null);}}>{[...new Set(seating.rows.map(r=>r.round))].map(n=><option key={n} value={n}>{n}</option>)}</select></label><table className="seating-grid"><thead><tr><th>{tr(locale,'Table','테이블')}</th><th>{tr(locale,'Participant codes','참가자 번호')}</th></tr></thead><tbody>{seating.rows.filter(r=>r.round===round).map(r=><tr key={r.table}><td>{r.table}</td><td>{r.left} ↔ {r.right}</td></tr>)}</tbody></table><details className="seating-roster"><summary>{tr(locale,'Host-only participant roster','호스트 전용 참가자 명단')}</summary><ul>{seating.roster.map(p=><li key={p.code}><strong>{p.code}</strong> {p.name}</li>)}</ul></details><p className="note">{tr(locale,'Share images use participant codes only. No names, photos or contact details are included.','공유 이미지에는 참가자 번호만 표시돼요. 이름, 사진, 연락처는 포함되지 않아요.')}</p>{!shareFile?<button className="admin-primary" onClick={()=>void prepareImage()}><Download size={18}/>{tr(locale,'Prepare Seating Image','좌석 배치 이미지 만들기')}</button>:<><Image src={shareUrl} alt={tr(locale,'Seating image preview','좌석 배치 이미지 미리보기')} width={1080} height={320+seating.rows.filter(r=>r.round===round).length*90} style={{width:'100%',height:'auto'}} unoptimized/><a className="admin-secondary" href={shareUrl} download={shareFile.name}><Download size={18}/>{tr(locale,'Download PNG','PNG 다운로드')}</a><button className="admin-primary" onClick={async()=>{try{if(navigator.canShare?.({files:[shareFile]}))await navigator.share({files:[shareFile],title:seating.event.title});else{const a=document.createElement('a');a.href=shareUrl;a.download=shareFile.name;a.click();}}catch(e){if(e instanceof Error&&e.name!=='AbortError')setError(e.message);}}}><Share2 size={18}/>{tr(locale,'Share Image','이미지 공유')}</button></>}</Modal>}
 </section>;
}
