'use client';
import { useEffect, useState, type ReactNode, type FormEvent } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, ArrowRight, ArrowLeft, CalendarDays, Clock3, MapPin, Compass, Heart, UserRound, Ticket, ShieldCheck, Check, Plus, X, ChevronRight, Search, LockKeyhole, Copy, LogOut } from 'lucide-react';
import QRCode from 'qrcode';
import { createClient } from '@/lib/supabase/client';
import { SignIn } from '@/components/sign-in';
import { VenueMap } from '@/components/venue-map';
import { PrivacyPolicy, TermsOfUse } from '@/components/legal';
import { SiteFooter } from '@/components/site-footer';
import { RoundyBrand } from '@/components/roundy-brand';
import { LocaleToggle } from '@/components/locale-toggle';
import { authConfigured } from '@/lib/auth-routing';
import { demoMode, events as sampleEvents, interests, emptyProfile, sampleProfile, profileComplete, dateLabel, timeLabel, type Event, type Profile, type Choice } from '@/lib/data';
import { dateLabelForLocale, localizeEvent, timeLabelForLocale, tr, type Locale } from '@/lib/locale';

type State={profile:Profile;applications:Record<string,string>;booked:Record<string,boolean>;checked:Record<string,boolean>;choices:Record<string,Choice>;finished:boolean;verification:string};
const initial:State={profile:emptyProfile,applications:{},booked:{},checked:{},choices:{},finished:false,verification:'Not started'};
async function api(path:string,body?:unknown,method?:string){const r=await fetch('/api/'+path,{method:method??(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error??'Something went wrong. Please try again.');return data;}
function headline(value:string){const minor=new Set(['a','an','and','as','at','but','by','for','in','of','on','or','the','to','via','vs','with']);const parts=value.replace(/[.!?]+$/,'').replace(/[.!?]+\s+/g,', ').split(/(\s+)/);const words=parts.map((part,index)=>/[A-Za-z]/.test(part)?index:-1).filter(index=>index>=0);const first=words[0];const last=words.at(-1);return parts.map((part,index)=>{if(!/[A-Za-z]/.test(part))return part;const lower=part.toLowerCase();return index!==first&&index!==last&&minor.has(lower)?lower:lower.replace(/[a-z]/,letter=>letter.toUpperCase());}).join('');}
function Button({children,href,onClick,secondary=false,disabled=false,type='button'}:{children:ReactNode;href?:string;onClick?:()=>void;secondary?:boolean;disabled?:boolean;type?:'button'|'submit'}){const cls='button'+(secondary?' secondary':'');return href?<Link className={cls} href={href}>{children}<ArrowRight size={18}/></Link>:<button className={cls} type={type} onClick={onClick} disabled={disabled}>{children}</button>;}
function Intro({label,title,body}:{label:string;title:string;body?:string}){return <div className="intro"><p className="eyebrow">{label}</p><h1>{headline(title)}</h1>{body&&<p className="description">{body}</p>}</div>;}
function Card({label,title,children}:{label?:string;title?:string;children?:ReactNode}){return <section className="info-card">{label&&<p className="eyebrow">{label}</p>}{title&&<h3>{headline(title)}</h3>}{children&&<div className="card-copy">{children}</div>}</section>;}
function Poster({title,label='SEOUL / AFTER HOURS'}:{title:string;label?:string}){return <div className="poster"><span className="eyebrow">{label}</span><strong>{title}</strong><span>A real room. A fresh start. <ArrowUpRight size={18}/></span></div>;}
function Note({children}:{children:ReactNode}){return <p className="note">{children}</p>;}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
function Empty({title,body,href,label='Explore events'}:{title:string;body:string;href?:string;label?:string}){return <div className="empty"><Heart size={40} strokeWidth={1.3}/><h2>{headline(title)}</h2><p>{body}</p>{href&&<Button href={href}>{label}</Button>}</div>;}

 function EventCard({e,locale}:{e:Event;locale:Locale}){const item=localizeEvent(e,locale);return <Link href={'/events/'+e.slug} className="event-card"><div className="event-photo"><Image src={e.image||'/images/yeouido.webp'} alt={e.neighborhood+tr(locale,' neighborhood scenery',' 지역 풍경')} fill sizes="(max-width: 640px) 100vw, 500px"/><span className="photo-tag">{item.theme}</span><span className="photo-arrow"><ArrowUpRight size={24}/></span></div><div className="event-copy"><p className="eyebrow">{e.neighborhood} <span>{e.seats_remaining}{tr(locale,' places left','자리 남음')}</span></p><h2>{headline(item.title)}</h2><p>{dateLabelForLocale(e.starts_at,locale)} · {timeLabelForLocale(e.starts_at,locale)} KST</p><div className="event-meta"><span>{e.age_min}–{e.age_max}{tr(locale,' years','세')}</span><span>{e.capacity/2}:{e.capacity/2} {tr(locale,'target','목표 비율')}</span><span>{tr(locale,'English only','영어로 진행')}</span></div></div></Link>;}
export function App({path}:{path:string}){
 const router=useRouter();const [state,setState]=useState<State>(initial);const [ready,setReady]=useState(false);const [events,setEvents]=useState<Event[]>(demoMode?sampleEvents:[]);const [authed,setAuthed]=useState(demoMode);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [filter,setFilter]=useState('All Seoul');const [query,setQuery]=useState('');const [round,setRound]=useState(1);const [quantity,setQuantity]=useState(1);const [qr,setQr]=useState('');const [matches,setMatches]=useState<Record<string,unknown>[]>([]);const [locale,setLocale]=useState<Locale>('en');
 const p=state.profile;const parts=path.split('/');const route=parts[0]||'home';const slug=(route==='onboarding'?parts[2]:parts[1])||'saturday-social';const event=events.find(e=>e.slug===slug);const appStatus=state.applications[slug];
 function patchProfile(values:Partial<Profile>){setState(s=>({...s,profile:{...s.profile,...values}}));}
 function flash(text:string){setMessage(text);setError('');}
 function setLanguage(next:Locale){setLocale(next);try{localStorage.setItem('roundy-locale',next);}catch{/* A blocked storage setting should not block language choice. */}}
 async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 useEffect(()=>{if(!authConfigured()){setReady(true);return;}if(demoMode){try{const saved=sessionStorage.getItem('who-demo-v1');if(saved)setState({...initial,...JSON.parse(saved)});}catch{/* A corrupt preview does not block browsing. */}setReady(true);}else{api('events').then(d=>setEvents(d.events)).catch(e=>setError(e.message));api('profile').then(d=>{setState(s=>({...s,profile:{...emptyProfile,...d.profile},verification:d.verification??'Not started'}));setAuthed(true);}).catch(()=>setAuthed(false)).finally(()=>setReady(true));}},[]);
 useEffect(()=>{if(ready&&demoMode){try{sessionStorage.setItem('who-demo-v1',JSON.stringify(state));}catch{setError('Photo is too large for this preview. Please choose a smaller photo.');}}},[state,ready]);
 useEffect(()=>{setError('');setMessage('');setQuery('');if(!demoMode&&authed){api('applications').then(d=>setState(s=>({...s,applications:Object.fromEntries(d.applications.map((a:{event_slug:string;status:string})=>[a.event_slug,a.status]))}))).catch(e=>setError(e.message));if(route==='matches')api(parts[1]?'matches/'+parts[1]:'matches').then(d=>setMatches(d.matches??[d.profile])).catch(e=>setError(e.message));}},[path,authed]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(route==='ticket'&&demoMode)QRCode.toDataURL('ROUNDY-DEMO-NOT-A-VALID-TICKET',{width:280,margin:2,color:{dark:'#20211f',light:'#fffefa'}}).then(setQr);},[route]);
 useEffect(()=>{try{const saved=localStorage.getItem('roundy-locale');if(saved==='en'||saved==='ko')setLocale(saved);}catch{/* Default English remains available. */}},[]);
 useEffect(()=>{document.documentElement.lang=locale;},[locale]);
 function goApply(e:Event){router.push(!authed?'/signin/'+e.slug:!profileComplete(p)?'/onboarding/basics/'+e.slug:'/applications/'+e.slug);}
 async function saveProfile(){if(!demoMode)await api('profile',p,'PUT');}
 const nav=[{href:'/discover',text:tr(locale,'Discover','둘러보기'),icon:Compass,on:['home','discover','events'].includes(route)},{href:'/me/events',text:tr(locale,'My Events','내 이벤트'),icon:CalendarDays,on:['applications','checkout','ticket','event-night'].includes(route)||path==='me/events'},{href:'/matches',text:tr(locale,'Matches','매칭'),icon:Heart,on:route==='matches'},{href:'/me',text:tr(locale,'Profile','프로필'),icon:UserRound,on:route==='me'&&path!=='me/events'}];

 let content:ReactNode;
 if(route==='home')content=<div className="landing"><div className="hero-copy"><p className="eyebrow">{tr(locale,'SEOUL. ENGLISH. REAL CONNECTIONS.','서울. 영어. 진짜 연결.')}</p><h1>{tr(locale,'Meet in Real Life,','오프라인에서 만나,')}<br/><span>{tr(locale,'See What Happens','어떤 일이 펼쳐질지 만나 보세요')}</span></h1><p>{tr(locale,'For people who would rather meet than swipe. A few good conversations. A real connection.','스와이프보다 만남을 선택하는 사람들을 위한 자리예요. 좋은 대화 몇 번, 그리고 진짜 연결.')}</p><Button href="/discover">{tr(locale,'Find your next evening','다음 저녁 찾기')}</Button><div className="hero-facts"><span><Clock3 size={18}/>{tr(locale,'15-minute conversations','15분 대화')}</span><span><LockKeyhole size={18}/>{tr(locale,'Only mutual matches','서로 선택한 매칭만')}</span></div></div><Poster title={tr(locale,'GOOD\nCOMPANY.','좋은\n인연.')}/><section className="landing-events"><div className="section-heading"><div><p className="eyebrow">{tr(locale,'OFFLINE, ON PURPOSE','오프라인에서, 의도적으로')}</p><h2>{tr(locale,'A Fresh Face,','새로운 얼굴,')}<br/>{tr(locale,'A Fresh Start','새로운 시작')}</h2></div><Link href="/discover">{tr(locale,'See all evenings','모든 이벤트 보기')} <ArrowUpRight size={18}/></Link></div><div className="event-grid">{events.map(e=><EventCard key={e.id} e={e} locale={locale}/>)}</div></section><div className="how-row">{locale==='ko'?[['01','이벤트 찾기','한 번만 지원하세요. 저희가 균형 잡힌 자리를 만들어요.'],['02','직접 만나기','넘길 프로필은 없어요. 두 사람을 위한 테이블만 있어요.'],['03','마음을 따라가기','서로 Yes를 선택했다면 대화를 이어 가세요.']]:[['01','Find your evening','Apply once. We curate a balanced room.'],['02','Actually meet','No profiles to scroll. Just a table for two.'],['03','Follow the spark','Both say Yes? Keep the conversation going.']].map(([n,t,b])=><div key={n}><span>{n}</span><h3>{headline(t)}</h3><p>{b}</p></div>)}</div><Button secondary href="/how-it-works">{tr(locale,'How it works & safety','이용 방법 및 안전')}</Button></div>;
 else if(route==='discover')content=<><Intro label={tr(locale,'DISCOVER','둘러보기')} title={tr(locale,'Who will you meet next?','다음에는 누구를 만날까요?')} body={tr(locale,'Small rooms. Good conversations. All in English.','작은 공간, 좋은 대화. 모두 영어로 진행돼요.')}/><div className="chips" aria-label={tr(locale,'Filter by neighborhood','지역으로 필터링')}>{['All Seoul','Yeouido','Anam'].map(x=><button aria-pressed={filter===x} className={filter===x?'chip selected':'chip'} onClick={()=>setFilter(x)} key={x}>{tr(locale,x,x==='All Seoul'?'서울 전체':x==='Yeouido'?'여의도':'안암')}</button>)}</div><div className="event-grid">{events.filter(e=>filter==='All Seoul'||e.neighborhood===filter).map(e=><EventCard key={e.id} e={e} locale={locale}/>)}</div>{events.length===0&&<Empty title={tr(locale,'New evenings are on their way.','새로운 이벤트를 준비하고 있어요.')} body={tr(locale,'Check back soon for published events.','공개된 이벤트가 있는지 곧 다시 확인해 주세요.')}/>}<div className="quiet-banner"><ShieldCheck size={24}/><div><h3>{tr(locale,'Good Chemistry, Clear Boundaries','좋은 케미, 분명한 경계')}</h3><p>{tr(locale,'No attendee browsing. Your profile stays private.','참가자 목록은 볼 수 없어요. 프로필은 비공개로 유지돼요.')}</p></div><Link aria-label={tr(locale,'Read safety policy','안전 정책 읽기')} href="/how-it-works"><ArrowUpRight/></Link></div></>;
 else if(route==='events'&&event){const item=localizeEvent(event,locale);content=<><div className="detail-photo"><Image src={event.image||'/images/yeouido.webp'} alt={event.neighborhood+tr(locale,' neighborhood atmosphere',' 지역 분위기')} fill sizes="(max-width: 640px) 100vw, 800px" priority/><span className="photo-tag">{event.neighborhood}{tr(locale,' neighborhood',' 지역')}</span></div><Intro label={event.neighborhood+' / '+item.theme} title={item.title} body={item.description}/><div className="detail-facts"><div><CalendarDays/><span><b>{dateLabelForLocale(event.starts_at,locale)}</b>{timeLabelForLocale(event.starts_at,locale)} – {timeLabelForLocale(event.ends_at,locale)} KST</span></div><div><Clock3/><span><b>{tr(locale,'Make time for a real conversation','진짜 대화를 위한 시간')}</b>{event.capacity/2}{tr(locale,' rounds · 15 minutes each','라운드 · 각 15분')}</span></div><div><MapPin/><span><b>{item.venue}</b>{item.address}</span></div></div><Card label={tr(locale,'THE ROOM','이벤트 정보')} title={tr(locale,`${event.capacity} people. A balanced room.`,`${event.capacity}명. 균형 있는 자리.`)}><div className="stats"><span><b>{event.capacity/2}:{event.capacity/2}</b>{tr(locale,'Target balance','목표 비율')}</span><span><b>{event.age_min}–{event.age_max}</b>{tr(locale,'Age range','연령대')}</span><span><b>{event.seats_remaining}</b>{tr(locale,'Places left','남은 자리')}</span></div><p>{tr(locale,'Korean & international participants. Profiles stay private until a mutual match.','한국인과 외국인 참가자가 함께해요. 서로 매칭되기 전까지 프로필은 비공개예요.')}</p></Card><VenueMap venue={item.venue} address={item.address} latitude={event.latitude} longitude={event.longitude} locale={locale}/><Card label={tr(locale,'BEFORE YOU APPLY','지원 전 확인')} title={tr(locale,'Come curious. Come as you are.','호기심을 가지고, 있는 그대로 오세요.')}><ul><li>{tr(locale,'Comfortable with 15-minute English conversations (rough guideline: TOEIC 780+).','15분 동안 영어로 대화할 수 있어야 해요 (대략 TOEIC 780+ 수준).')}</li><li>{tr(locale,'Bring a valid photo ID. Arrive 15 minutes early.','유효한 사진 신분증을 지참하고 15분 일찍 도착해 주세요.')}</li><li>{tr(locale,'No alcohol provided. No contact exchange during the event.','주류는 제공하지 않으며, 이벤트 중 연락처 교환은 하지 않아요.')}</li><li>{tr(locale,'Choose privately. At most 3 Yes choices. Only mutual Yes makes a match.','개인적으로 선택하세요. Yes는 최대 3명이며, 서로 Yes를 선택해야 매칭돼요.')}</li></ul></Card>{demoMode&&<Note>{tr(locale,'Illustrative event. Neighborhood imagery is from 1 Cup English; it is not a venue photograph.','예시 이벤트예요. 지역 이미지는 1 Cup English에서 가져왔으며 실제 장소 사진이 아니에요.')}</Note>}<div className="sticky-action"><div><b>{dateLabelForLocale(event.starts_at,locale)}</b><span>{event.seats_remaining}{tr(locale,' places remaining','자리 남음')}</span></div><Button onClick={()=>goApply(event)}>{tr(locale,'Apply for this evening','이 이벤트 지원하기')} <ArrowRight size={18}/></Button></div></>;}
 else if(route==='signin')content=<SignIn eventSlug={parts[1]} locale={locale}/>;
 else if(route==='onboarding'){
 const steps=['basics','photos','work','interests','contact','verification'];const step=steps.indexOf(parts[1]);const titles=['First, the basics.','A face they’ll remember.','A little more about you.','Choose what you’re really into.','A way to keep talking.','Real people. Real evenings.'];
 async function next(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await work(async()=>{if(step===0&&(!p.gender||new Date(p.birth_date)>new Date(new Date().setFullYear(new Date().getFullYear()-18))))throw new Error('You must be 18 or older and select a gender.');if(step===1&&p.photos.length<1)throw new Error('Please add at least one photo.');if(step===3&&p.interests.length<3)throw new Error('Choose at least 3 interests.');await saveProfile();if(step===5){const instagram=String(form.get('instagram')||'');const linkedin=String(form.get('linkedin')||'');if(!instagram&&!linkedin)throw new Error('Add a public social account, or choose Apply while I arrange verification.');if(!demoMode)await api('verification',{instagram,linkedin});setState(s=>({...s,verification:'Reviewing'}));router.push('/applications/'+slug);}else router.push('/onboarding/'+steps[step+1]+'/'+slug);});}
 content=<><div className="progress-label"><button className="icon-button" aria-label="Previous step" onClick={()=>step>0?router.push('/onboarding/'+steps[step-1]+'/'+slug):router.push('/discover')}><ArrowLeft size={20}/></button><span>PROFILE {step+1} / 6</span><Link href="/me">Save & leave</Link></div><progress max={6} value={step+1}/><Intro label="YOUR REUSABLE PROFILE" title={titles[step]??'Your profile'} body={['Your legal name stays private until a mutual match.','Add 1–3 recent photos. Keep it clearly, honestly you.','We display a general description of your work. Exact details stay private.','Pick at least 3, up to 10. Small details make you memorable.','Only mutual matches receive your name and phone number.','Our team reviews your public social account. Handles stay private.'][step]}/><form onSubmit={next}>
 {step===0&&<><Field label="FULL LEGAL NAME"><input autoComplete="name" required value={p.full_name} onChange={e=>patchProfile({full_name:e.target.value})} placeholder="Your name as shown on ID"/></Field><Field label="DATE OF BIRTH"><input type="date" required value={p.birth_date} onChange={e=>patchProfile({birth_date:e.target.value})}/></Field><fieldset><legend>Gender</legend><div className="chips">{[['female','Woman'],['male','Man']].map(([v,l])=><button type="button" className={'chip '+(p.gender===v?'selected':'')} aria-pressed={p.gender===v} onClick={()=>patchProfile({gender:v})} key={v}>{l}</button>)}</div></fieldset><Field label="NATIONALITY"><input required value={p.nationality} onChange={e=>patchProfile({nationality:e.target.value})} placeholder="Your nationality"/></Field></>}
 {step===1&&<><div className="photo-grid">{p.photos.map((photo,i)=><div className={'profile-photo '+(i===0?'primary-photo':'')} key={photo}>{photo==='sample-avatar'?<UserRound size={64}/>:<Image src={photo} alt={'Your photo '+(i+1)} fill unoptimized sizes="200px"/>}<span>{i===0?'Main photo':'Photo '+(i+1)}</span><button aria-label={'Remove photo '+(i+1)} className="photo-remove" type="button" onClick={()=>patchProfile({photos:p.photos.filter((_,j)=>j!==i)})}><X size={16}/></button>{i>0&&<button className="make-main" type="button" onClick={()=>patchProfile({photos:[photo,...p.photos.filter((_,j)=>j!==i)]})}>Make main</button>}</div>)}{p.photos.length<3&&<label className="photo-add"><Plus size={32}/><span>Add photo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;void work(async()=>{if(file.size>2*1024*1024)throw new Error('Please choose an image below 2 MB.');if(demoMode){const value=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});patchProfile({photos:[...p.photos,value]});}else{const form=new FormData();form.set('photo',file);const r=await fetch('/api/photos',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);patchProfile({photos:[...p.photos,data.url]});}});}}/></label>}</div><Note>No group photos or heavy filters. Use a recent, recognizable picture.</Note></>}
 {step===2&&<><Field label="HEIGHT (CM)"><input type="number" min={100} max={250} required value={p.height_cm} onChange={e=>patchProfile({height_cm:Number(e.target.value)})}/></Field><Field label="JOB TITLE"><input required value={p.job_title} onChange={e=>patchProfile({job_title:e.target.value})} placeholder="Product designer"/></Field><Field label="WORKPLACE / SCHOOL — PRIVATE"><input required value={p.workplace} onChange={e=>patchProfile({workplace:e.target.value})} placeholder="Company or university"/></Field><Field label="PUBLIC JOB DESCRIPTION"><input required value={p.public_job} onChange={e=>patchProfile({public_job:e.target.value})} placeholder="Designer"/></Field><Field label="PUBLIC WORKPLACE DESCRIPTION"><input required value={p.public_workplace} onChange={e=>patchProfile({public_workplace:e.target.value})} placeholder="A creative company"/></Field></>}
 {step===3&&<><Field label="SEARCH INTERESTS"><span className="search-input"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you into?"/></span></Field><div className="chips interests">{interests.filter(i=>i.toLowerCase().includes(query.toLowerCase())).map(i=><button type="button" key={i} aria-pressed={p.interests.includes(i)} className={'chip '+(p.interests.includes(i)?'selected':'')} onClick={()=>{if(!p.interests.includes(i)&&p.interests.length>=10){setError('Choose up to 10 interests.');return;}patchProfile({interests:p.interests.includes(i)?p.interests.filter(v=>v!==i):[...p.interests,i]});}}>{p.interests.includes(i)&&<Check size={14}/>} {i}</button>)}</div><Note>{p.interests.length} / 10 selected</Note></>}
 {step===4&&<><Field label="PRIVATE PHONE NUMBER"><input type="tel" required pattern="\+?[0-9\s\-]{8,20}" value={p.phone} onChange={e=>patchProfile({phone:e.target.value})} placeholder="+82 10 1234 5678"/></Field><label className="check-row"><input type="checkbox" required checked={p.contact_consent} onChange={e=>patchProfile({contact_consent:e.target.checked})}/><span>I agree to share my name and phone number with mutual matches after the event.</span></label><Card label="ONLY WHEN IT’S MUTUAL" title="Your contact details stay private.">Sharing happens only after you both choose Yes. Once revealed, contact details cannot be revoked.</Card></>}
 {step===5&&<><Field label="PUBLIC INSTAGRAM"><input name="instagram" type="url" placeholder="https://instagram.com/yourname"/></Field><Field label="OR LINKEDIN"><input name="linkedin" type="url" placeholder="https://linkedin.com/in/yourname"/></Field><Card label="NO SOCIAL ACCOUNT?" title="Use work or student proof.">Apply now, then arrange a private document review with your host. Verification must clear before attending.</Card><Button secondary onClick={()=>work(async()=>{await saveProfile();router.push('/applications/'+slug);})}>Apply while I arrange verification</Button></>}
 <Button type="submit" disabled={busy}>{busy?'Saving…':step===5?'Submit for review':'Continue'} {!busy&&<ArrowRight size={18}/>}</Button></form>{demoMode&&<button className="text-button" onClick={()=>{setState(s=>({...s,profile:sampleProfile}));flash('Fictional sample profile loaded. You can edit it or continue.');}}>Fill with a fictional sample profile</button>}</>;
 }
 else if(route==='applications'&&event){content=<><Intro label="APPLICATION" title={appStatus==='Approved'?'We saved you a place.':appStatus==='Waitlisted'?'A little patience.':appStatus==='Reviewing'?'You’re on our radar.':'One evening. Your kind of people.'} body={appStatus==='Approved'?'Confirm your place with an existing ticket or checkout.':appStatus==='Waitlisted'?'We’ll let you know if a suitable place opens.':appStatus==='Reviewing'?'We’re reviewing your application and balancing the room.':'Your saved profile comes with you. No long forms.'}/><Card label={appStatus??'SATURDAY SOCIAL'} title={event.title}>{dateLabel(event.starts_at)} · {timeLabel(event.starts_at)}<br/>{event.neighborhood} · English only</Card>{appStatus?appStatus==='Approved'?<Button href={'/checkout/'+slug}>Confirm my seat</Button>:<Button href="/me/events">Back to My Events</Button>:<><Card label="BEFORE YOU APPLY" title="A good fit for the room">You can comfortably hold a 15-minute English conversation and agree to our <Link href="/how-it-works">event rules</Link>. Applying does not confirm a seat.</Card><Button disabled={busy} onClick={()=>work(async()=>{if(!authed){router.push('/signin/'+slug);return;}if(!profileComplete(p)){router.push('/onboarding/basics/'+slug);return;}if(!demoMode)await api('applications',{eventId:event.id});setState(s=>({...s,applications:{...s.applications,[slug]:'Reviewing'}}));})}>Send application</Button></>}{demoMode&&appStatus&&<div className="demo-controls"><p>Preview application states</p><div className="chips">{['Reviewing','Waitlisted','Approved'].map(s=><button key={s} className={'chip '+(appStatus===s?'selected':'')} onClick={()=>setState(d=>({...d,applications:{...d.applications,[slug]:s}}))}>{s}</button>)}</div></div>}</>;}
 else if(route==='checkout'&&event){const total=(p.gender==='female'?19800:29800)*quantity;content=appStatus!=='Approved'?<Empty title="Approval comes first." body="Apply for this evening and wait for your seat approval before checkout." href={'/applications/'+slug} label="View application"/>:<><Intro label="CHECKOUT" title="Make it official." body={'You’re approved for '+event.title+'.'}/><div className="ticket-options">{[1,3].map(n=><button key={n} className={'ticket-option '+(n===quantity?'selected':'')} onClick={()=>setQuantity(n)}><Ticket/><b>{n} {n===1?'ticket':'tickets'}</b><span>Valid for 90 days</span></button>)}</div><div className="price-row"><span>{quantity} {quantity===1?'ticket':'tickets'}</span><strong>₩{total.toLocaleString()}</strong></div><Note>Women ₩19,800 / Men ₩29,800 per ticket. Returning attendees receive 10% off the server-verified price. Promo/referral support awaits the payment adapter.</Note><Card label="BEFORE YOU PAY" title="Valid for 90 days">100% refund if requested within 90 days. No refund after expiry. Tickets are personal and non-transferable. One ticket is used for this booking.</Card><Button disabled={busy} onClick={()=>work(async()=>{if(!demoMode){await api('checkout',{eventId:event.id,quantity});return;}setState(s=>({...s,booked:{...s.booked,[slug]:true}}));router.push('/ticket/'+slug);})}>{demoMode?'Preview confirmed booking — no charge':'Continue to secure payment'}</Button><Button secondary onClick={()=>work(async()=>{if(demoMode){setState(s=>({...s,booked:{...s.booked,[slug]:true}}));router.push('/ticket/'+slug);}else{await api('bookings',{eventId:event.id});router.push('/ticket/'+slug);}})}>Use an existing ticket</Button></>;}
 else if(route==='ticket'&&event)content=(!demoMode||!state.booked[slug])?<Empty title="Your ticket lives here." body={demoMode?'Confirm your approved booking to unlock your ticket.':'Live QR ticket issuance is pending the payment/check-in integration.'} href={'/applications/'+slug} label="View application"/>:<><Intro label="BOOKING CONFIRMED" title="See you there." body="Show your ticket and photo ID to the host."/><div className="qr-card">{qr&&<Image src={qr} alt="Demo QR code, not a valid admission ticket" width={230} height={230}/>}<b>PREVIEW TICKET — NOT VALID FOR ENTRY</b></div><Card label={event.title} title={dateLabel(event.starts_at)+' · '+timeLabel(event.starts_at)}>{event.neighborhood}<br/>Arrive 15 minutes early. Entry closes 15 minutes after the start.</Card><Note>Your starting table appears only after a host checks you in. Verification and ID are required.</Note><div className="demo-controls"><p>Event-night preview</p><Button onClick={()=>{setState(s=>({...s,checked:{...s.checked,[slug]:true}}));router.push('/event-night/'+slug);}}>Preview staff check-in</Button></div></>;
 else if(route==='event-night'&&event){const key=slug+':'+round;const count=Object.entries(state.choices).filter(([k,c])=>k.startsWith(slug+':')&&c==='yes').length;const choice=state.choices[key];content=!demoMode?<Empty title="The host starts your evening." body="Live table assignment and host controls are pending integration. Your privacy remains protected."/>:!state.checked[slug]?<Empty title="Check in first." body="Your host must verify your ticket and ID before a table is revealed." href={'/ticket/'+slug} label="Open ticket"/>:state.finished?<><Intro label="EVENT COMPLETE" title="Thanks for showing up." body="Your choices are locked. Only mutual Yes creates a match."/><Button href="/matches">View match results</Button></>:<><Intro label={'ROUND '+round+' / 6'} title="Be here. Be curious." body="There’s no perfect opening line. Just say hello."/><div className="timer"><p className="eyebrow">TABLE {String((round+1)%6+1).padStart(2,'0')}</p><strong>15:00</strong><span>15-minute round · preview timer</span><p>Next table: {String((round+2)%6+1).padStart(2,'0')}</p></div><h2>Would You Like to Meet Again</h2><p className="description">Your answer stays private. Edit until the evening ends.</p><div className="choice-row">{(['no','maybe','yes'] as Choice[]).map(c=><button key={c} aria-pressed={choice===c} className={'choice '+(choice===c?'chosen':'')} onClick={()=>{if(c==='yes'&&choice!=='yes'&&count>=3){setError('You can choose Yes for at most 3 people. Change an earlier Yes to choose someone else.');return;}setError('');setState(s=>({...s,choices:{...s.choices,[key]:c}}));}}>{c==='no'?<X/>:c==='yes'?<Heart/>:<span>?</span>}{c[0].toUpperCase()+c.slice(1)}</button>)}</div><Note>{count} / 3 Yes choices used. Your choice is saved locally in this preview.</Note><div className="round-pagination">{[1,2,3,4,5,6].map(n=><button aria-label={'Review round '+n} className={round===n?'selected':''} key={n} onClick={()=>setRound(n)}>{n}</button>)}</div>{round<6?<Button onClick={()=>setRound(round+1)}>Next round</Button>:<Button onClick={()=>setState(s=>({...s,finished:true}))}>Finish preview & lock choices</Button>}</>;}
 else if(route==='matches')content=demoMode?<><Intro label="MATCHES" title={state.finished?'A good evening is a good start.':'Good things happen offline.'} body={state.finished?'No mutual matches in this preview. Your private choices stay private.':'After an evening, this is where mutual connections appear.'}/><Empty title="A connection takes two." body="Only Yes + Yes creates a match. Nobody sees rejections, and contact details stay hidden until there is a real mutual match." href="/discover"/>{state.finished&&<Card label="WHY NO PREVIEW MATCH?" title="We never invent someone’s Yes.">This local preview has no second attendee. The database implements reciprocal matching for real events.</Card>}</>:<><Intro label="MATCHES" title="The feeling is mutual." body="Your connections, from evenings you actually shared."/>{matches.length===0?<Empty title="No mutual matches yet." body="Your results appear when your event closes."/>:matches.map((m,i)=><Card key={i} label="MUTUAL MATCH" title={String(m.full_name??'A new connection')}>{m.phone?<><p>{String(m.public_job??'')} at {String(m.public_workplace??'')}</p><Button onClick={()=>void navigator.clipboard.writeText(String(m.phone)).then(()=>flash('Phone number copied.')).catch(()=>setError('Could not copy. Please select the number manually.'))}><Copy size={18}/>{String(m.phone)}</Button></>:<Button href={'/matches/'+String(m.id)}>Open matched profile</Button>}</Card>)}</>;
 else if(route==='me'){
 const sub=parts[1]??'';
 if(sub==='events')content=<><Intro label="MY EVENTS" title="Your plans. Your possibilities." body="Everything coming up, all in one place."/>{events.filter(e=>state.applications[e.slug]||state.booked[e.slug]).map(e=><Card key={e.id} label={state.booked[e.slug]?'CONFIRMED':state.applications[e.slug]} title={e.title}><p>{dateLabel(e.starts_at)} · {e.neighborhood}</p><Button href={(state.booked[e.slug]?'/ticket/':'/applications/')+e.slug}>{state.booked[e.slug]?'Open ticket':'View application'}</Button></Card>)}{Object.keys(state.applications).length===0&&<Empty title="Make a little room for someone new." body="Your applications and confirmed evenings will appear here." href="/discover"/>}</>;
 else if(sub==='tickets')content=<><Intro label="MY TICKETS" title="Good evenings ahead." body="Tickets are personal and valid for 90 days."/><Poster title={'00\nTICKETS'} label="AVAILABLE BALANCE"/><Note>{demoMode?'Preview bookings do not purchase or issue real credits.':'Live credit balance UI is pending integration.'}</Note><Button href="/discover">Find an evening</Button><Card label="REFUNDS" title="Your 90-day window">Request a refund within 90 days for a 100% refund under the stated policy. No refund after expiry. The treatment of used tickets needs policy clarification before automated refunds go live.</Card></>;
 else if(sub==='verification')content=<><Intro label="VERIFICATION" title="Real people. Real evenings." body="Your account details stay between you and our team."/><Card label={state.verification.toUpperCase()} title={state.verification==='Reviewing'?'We’re reviewing your account.':'Complete your verification'}>Social handles are never revealed to attendees. Changing your social account resets verification. Verification must clear before attending.</Card><Button href="/onboarding/verification/saturday-social">Update verification</Button></>;
 else if(sub==='safety')content=<><Intro label="SAFETY" title="Everyone deserves a good evening." body="Reports are confidential, not anonymous. Our team reviews them directly."/><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void work(async()=>{if(!demoMode)await api('reports',{reason:form.get('reason'),context:form.get('context')});flash(demoMode?'Preview only. No report was sent.':'Your report was submitted for private review.');});}}><Field label="EVENT / ENCOUNTER"><input name="context" required placeholder="Event date and round or match"/></Field><Field label="WHAT HAPPENED?"><textarea name="reason" required minLength={10} placeholder="Describe your concern" rows={5}/></Field><Button type="submit" disabled={busy}>Send a confidential report</Button></form><Note>Harassment, intoxication, hate speech, unwanted contact, recording and sharing identities can lead to permanent removal. <Link href="/how-it-works">Read our safety principles.</Link></Note></>;
 else if(sub==='settings')content=<><Intro label="SETTINGS" title="Make yourself at home."/><Button secondary href="/onboarding/contact/saturday-social">Update contact details</Button><Button secondary href="/how-it-works">Privacy & event rules</Button><Button onClick={()=>work(async()=>{if(!demoMode){const {error}=await createClient().auth.signOut();if(error)throw error;}setState(initial);setAuthed(demoMode);router.push('/');router.refresh();})}><LogOut size={18}/>{demoMode?'Reset this preview':'Sign out'}</Button></>;
 else content=<><Intro label="PROFILE" title={p.full_name?'Hello, '+p.full_name.split(' ')[0]+'.':'A little more you.'} body="One profile. Every evening."/><div className="profile-summary"><span className="avatar"><UserRound size={40}/></span><div><h2>{headline(profileComplete(p)?'Your profile is ready.':'Let’s get to know you.')}</h2><p>{profileComplete(p)?'Ready to apply for an evening.':'Complete your profile when you apply.'}</p></div></div><Button href="/onboarding/basics/saturday-social">{profileComplete(p)?'Edit profile':'Complete profile'}</Button><div className="menu-list">{[['events','My Events',CalendarDays],['tickets','Tickets & credits',Ticket],['verification','Verification',ShieldCheck],['safety','Safety & reporting',Heart],['settings','Settings',UserRound]].map(([url,title,Icon])=>{const I=Icon as typeof Heart;return <Link key={String(url)} href={'/me/'+url}><I size={22}/><span>{String(title)}</span><ChevronRight size={18}/></Link>;})}</div></>;
 }
 else if(route==='how-it-works')content=<><Intro label="HOW IT WORKS & SAFETY" title="Good chemistry. Clear boundaries." body="Discover events online. Discover people offline."/>{[['01 / JOIN','Find your evening','Create a reusable profile, apply, and wait for a curated room. Once approved, use a ticket or checkout.'],['02 / MEET','A table for two','Bring ID and arrive early. Meet through 15-minute English rounds. No alcohol is provided. Entry closes 15 minutes after the start.'],['03 / CONNECT','Only when it is mutual','Choose up to 3 Yes. Both say Yes? You see each other’s profile, name and phone number after the event.']].map(([label,title,body])=><Card key={label} label={label} title={title}>{body}</Card>)}<Card label="PRIVACY" title="No roster. No endless browsing.">Photos, identity, social handles and choices are private. Rich dating profiles and phone numbers are available only to mutual matches. Verification handles are never shared.</Card><Card label="SAFETY" title="Respect is the entry requirement.">Harassment, hate speech, intoxication, recording and sharing identities can lead to immediate removal and permanent exclusion. Reports identify the reporter to staff only. Reported pairs should not be seated together in future events.</Card><Button href="/me/safety">Report a concern</Button><Button secondary href="/discover">Explore events</Button></>;
 else if(route==='terms')content=<TermsOfUse locale={locale}/>;
 else if(route==='privacy')content=<PrivacyPolicy locale={locale}/>;
 else content=<Empty title={tr(locale,'This page isn’t here.','이 페이지를 찾을 수 없어요.')} body={tr(locale,'Let’s find your next evening instead.','대신 다음 이벤트를 찾아 볼까요?')} href="/discover" label={tr(locale,'Explore events','이벤트 둘러보기')}/>;
 const wide=['home','discover'].includes(route);const privateRoute=['onboarding','applications','checkout','ticket','event-night','matches','me'].includes(route);
 if(!demoMode&&ready&&!authed&&privateRoute)content=<Empty title={tr(locale,'Your evenings are personal.','당신의 저녁은 개인적인 시간이에요.')} body={tr(locale,'Sign in to manage your profile, tickets and matches.','로그인하고 프로필, 티켓, 매칭을 관리하세요.')} href={'/signin/'+slug} label={tr(locale,'Sign in','로그인')}/>;
 return <div className={"experience route-"+route}><a className="skip" href="#main">{tr(locale,'Skip to content','본문으로 건너뛰기')}</a><header className="site-header"><Link className="wordmark" href="/"><RoundyBrand/></Link><nav aria-label={tr(locale,'Desktop navigation','데스크톱 내비게이션')}>{nav.map(n=><Link className={n.on?'active':''} key={n.href} href={n.href}>{n.text}</Link>)}</nav><LocaleToggle locale={locale} onChange={setLanguage}/><Link className="header-signin" href={authed?"/me":"/signin"}>{authed?tr(locale,'My Profile','내 프로필'):tr(locale,'Sign In','로그인')}</Link></header>{demoMode&&<div className="preview-strip">{tr(locale,'Interactive preview','인터랙티브 미리보기')} <span>{tr(locale,'· Sample events · No payments or messages sent','· 예시 이벤트 · 결제나 메시지는 전송되지 않아요')}</span></div>}<main id="main" className={'content '+(wide?'wide':'narrow')} aria-busy={busy}>{!ready&&privateRoute?<p>{tr(locale,'Loading your account…','계정을 불러오는 중…')}</p>:content}{error&&<div role="alert" className="feedback error">{error}</div>}{message&&<div role="status" className="feedback">{message}</div>}</main><SiteFooter locale={locale}/>{!['onboarding','signin'].includes(route)&&<nav className="bottom-nav" aria-label={tr(locale,'Main navigation','주요 내비게이션')}>{nav.map(n=><Link aria-current={n.on?'page':undefined} className={n.on?'active':''} href={n.href} key={n.href}><n.icon size={22} strokeWidth={n.on?2:1.5}/><span>{n.text}</span></Link>)}</nav>}</div>;
}
