'use client';

import { FormEvent, useEffect, useState } from 'react';
import Image from 'next/image';
import { ArrowLeft, Clock3, MessageCircle, Search, Send, UserRound, X } from 'lucide-react';
import { StreamChat } from 'stream-chat';
import { LoadingScreen } from './loading-screen';
import { MATCH_CHAT_MAX_MESSAGE_LENGTH } from '@/lib/match-chat';
import { tr, type Locale } from '@/lib/locale';

type ChatState='awaiting_opening'|'awaiting_reply'|'active'|'expired';
type InboxChannel={key:string;kind:'roundy'|'match'|'expired';channelType:string|null;channelId:string|null;title:string;photo:string|null;matchId:string|null;chatState:ChatState;deadline:string|null;canSend:boolean;firstMessageByViewer:boolean};
type InboxResponse={apiKey:string;token:string;streamUserId:string;channels:InboxChannel[]};
type ChatMessage={id:string;text:string;createdAt:string|null;senderId:string};

function toMessages(values:unknown[]):ChatMessage[]{return values.flatMap(value=>{if(!value||typeof value!=='object')return [];const item=value as {id?:unknown;text?:unknown;created_at?:unknown;user?:{id?:unknown};user_id?:unknown};if(typeof item.id!=='string'||typeof item.text!=='string')return [];return [{id:item.id,text:item.text,createdAt:typeof item.created_at==='string'?item.created_at:null,senderId:typeof item.user?.id==='string'?item.user.id:typeof item.user_id==='string'?item.user_id:''}];});}
function mergeMessage(previous:ChatMessage[],next:ChatMessage){const index=previous.findIndex(message=>message.id===next.id);if(index<0)return [...previous,next];const copy=[...previous];copy[index]=next;return copy;}
function deadlineLabel(channel:InboxChannel,locale:Locale,now:number){if(channel.kind==='roundy')return tr(locale,'Official updates','공식 안내');if(channel.chatState==='expired')return tr(locale,'Expired','만료됨');if(!channel.deadline)return '';const hours=Math.ceil((Date.parse(channel.deadline)-now)/3_600_000);if(hours<=0)return tr(locale,'Expired','만료됨');return hours>24?tr(locale,`${Math.ceil(hours/24)} days left`,`${Math.ceil(hours/24)}일 남음`):tr(locale,`${hours} hours left`,`${hours}시간 남음`);}
function phaseCopy(channel:InboxChannel,locale:Locale){if(channel.chatState==='awaiting_opening')return tr(locale,'Either of you can send the first message within 72 hours.','두 사람 중 누구나 72시간 안에 첫 메시지를 보낼 수 있어요.');if(channel.chatState==='awaiting_reply')return channel.firstMessageByViewer?tr(locale,'Waiting for a reply within the 72-hour window.','상대방의 72시간 이내 답장을 기다리고 있어요.'):tr(locale,'Send one reply within 72 hours to unlock the chat.','72시간 안에 답장 하나를 보내면 대화가 열려요.');if(channel.chatState==='active')return tr(locale,'Conversation unlocked.','대화가 열렸어요.');return tr(locale,'This match expired and its chat was deleted.','이 매칭은 만료되어 채팅방이 삭제되었어요.');}
function Avatar({channel}:{channel:InboxChannel}){const [failed,setFailed]=useState(false);if(channel.kind==='roundy')return <span className="inbox-avatar roundy-avatar" aria-label="Roundy Team">R</span>;return <span className={'inbox-avatar'+(channel.kind==='expired'?' expired':'')}>{channel.photo&&!failed?<Image src={channel.photo} alt="" fill sizes="48px" unoptimized onError={()=>setFailed(true)}/>:<UserRound size={22}/>}</span>;}

export function MatchesScreen({locale}:{locale:Locale}){
 const [search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false);
 const [inbox,setInbox]=useState<InboxResponse|null>(null),[messages,setMessages]=useState<Record<string,ChatMessage[]>>({}),[selectedKey,setSelectedKey]=useState('roundy');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[sendError,setSendError]=useState(''),[mobileConversation,setMobileConversation]=useState(false),[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setInbox(null);setMessages({});void fetch('/api/chat/inbox',{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load your inbox.');return data as InboxResponse;}).then(data=>{if(!controller.signal.aborted){setInbox(data);setSelectedKey(previous=>data.channels.some(channel=>channel.key===previous)?previous:'roundy');}}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:tr(locale,'Could not load your inbox.','메시지를 불러오지 못했어요.'));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[locale,retry]);
 useEffect(()=>{if(!inbox)return;let active=true;const cleanups:(()=>void)[]=[];const client=StreamChat.getInstance(inbox.apiKey);void (async()=>{try{if(client.userID&&client.userID!==inbox.streamUserId)await client.disconnectUser();await client.connectUser({id:inbox.streamUserId},inbox.token);for(const entry of inbox.channels){if(!entry.channelType||!entry.channelId)continue;const channel=client.channel(entry.channelType,entry.channelId);await channel.watch();if(!active)return;setMessages(previous=>({...previous,[entry.key]:toMessages(channel.state.messages)}));const listener=channel.on('message.new',event=>{if(!active||!event.message)return;const [message]=toMessages([event.message]);if(message)setMessages(previous=>({...previous,[entry.key]:mergeMessage(previous[entry.key]??[],message)}));});cleanups.push(()=>listener.unsubscribe());}}catch(reason){if(active)setError(reason instanceof Error?reason.message:tr(locale,'Could not connect to chat.','채팅에 연결하지 못했어요.'));}})();return()=>{active=false;cleanups.forEach(cleanup=>cleanup());void client.disconnectUser();};},[inbox,locale]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),60_000);return()=>window.clearInterval(timer);},[]);
 const selected=inbox?.channels.find(channel=>channel.key===selectedKey)??inbox?.channels[0]??null;
 async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const text=draft.trim();if(!selected?.matchId||!selected.canSend||!text||sending)return;setSending(true);setSendError('');try{const response=await fetch('/api/chat/matches/'+encodeURIComponent(selected.matchId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,messageId:crypto.randomUUID()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not send your message.');setDraft('');}catch(reason){setSendError(reason instanceof Error?reason.message:tr(locale,'Could not send your message.','메시지를 보내지 못했어요.'));}finally{setSending(false);}}
 if(loading)return <LoadingScreen/>;
 if(error&&!inbox)return <section className="matches-empty"><MessageCircle size={36}/><h1>{tr(locale,'Could not load your inbox','메시지를 불러오지 못했어요')}</h1><p role="alert">{error}</p><button className="button" onClick={()=>setRetry(value=>value+1)}>{tr(locale,'Try again','다시 시도')}</button></section>;
 if(!selected)return null;
 const conversationMessages=messages[selected.key]??[];
 function openConversation(channel:InboxChannel){setSelectedKey(channel.key);setMobileConversation(true);setDraft('');setSendError('');}
 function preview(channel:InboxChannel){if(channel.kind==='expired')return tr(locale,'Match expired','매칭 만료');const last=messages[channel.key]?.at(-1);return last?.text??(channel.kind==='roundy'?tr(locale,'Welcome and updates from Roundy','Roundy의 환영 메시지와 안내'):tr(locale,'Say hello to your match','매칭 상대에게 인사해 보세요'));}
 const newMatches=(inbox?.channels??[]).filter(channel=>channel.chatState==='awaiting_opening');
 const visibleChannels=(inbox?.channels??[]).filter(channel=>(channel.title+' '+preview(channel)).toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <section className={'stream-inbox'+(mobileConversation?' mobile-conversation':'')}><aside className="inbox-sidebar" aria-label={tr(locale,'Inbox conversations','메시지 목록')}><header><button className="icon-button" aria-label={tr(locale,'Search conversations','대화 검색')} aria-expanded={searchOpen} onClick={()=>{setSearchOpen(!searchOpen);setSearch('');}}>{searchOpen?<X size={22}/>:<Search size={22}/>}</button></header>
   {searchOpen&&<label className="inbox-search"><Search size={18}/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder={tr(locale,'Search by name or message','이름 또는 메시지 검색')}/></label>}
   {!search&&newMatches.length>0&&<section className="inbox-new-matches"><h2>{tr(locale,'Your matches','새로운 매칭')} <span>{newMatches.length}</span></h2><div className="inbox-match-strip">{newMatches.map(channel=><button key={channel.key} onClick={()=>openConversation(channel)}><Avatar channel={channel}/><strong>{channel.title.split(' ')[0]}</strong><small>{deadlineLabel(channel,locale,now)}</small></button>)}</div></section>}
   <h2 className="inbox-section-heading">{tr(locale,'Conversations','대화')}</h2>
   {error&&<p className="inbox-connection-error" role="alert">{tr(locale,'Could not connect.','연결하지 못했어요.')} <button onClick={()=>setRetry(value=>value+1)}>{tr(locale,'Retry','다시 시도')}</button></p>}
   <div className="inbox-list">{visibleChannels.map(channel=><button key={channel.key} className={'inbox-row '+(channel.key===selected.key?'selected':'')} onClick={()=>openConversation(channel)} aria-pressed={channel.key===selected.key&&mobileConversation}><Avatar channel={channel}/><span><strong>{channel.title}</strong><small>{preview(channel)}</small></span>{channel.chatState==='awaiting_reply'&&!channel.firstMessageByViewer?<span className="inbox-turn">{tr(locale,'Your turn','답장할 차례')}</span>:channel.kind==='expired'?<Clock3 size={16}/>:null}</button>)}{visibleChannels.length===0&&<p className="inbox-no-results">{tr(locale,'No conversations found.','검색된 대화가 없어요.')}</p>}</div></aside><article className="inbox-conversation"><header className="inbox-conversation-header"><button className="icon-button inbox-back" aria-label={tr(locale,'Back to conversations','메시지 목록으로 돌아가기')} onClick={()=>setMobileConversation(false)}><ArrowLeft size={20}/></button><Avatar key={selected.key} channel={selected}/><div><h2>{selected.title}</h2><p>{deadlineLabel(selected,locale,now)}</p></div></header>{selected.kind==='expired'?<div className="inbox-expired"><Clock3 size={25}/><h3>{tr(locale,'Match expired','매칭이 만료되었어요')}</h3><p>{phaseCopy(selected,locale)}</p></div>:<>{selected.kind==='match'&&selected.chatState!=='active'&&<p className="inbox-phase"><Clock3 size={16}/>{phaseCopy(selected,locale)}</p>}<div className="inbox-messages" aria-live="polite">{conversationMessages.length===0&&<p className="inbox-start-note">{selected.kind==='roundy'?tr(locale,'Your Roundy updates will appear here.','Roundy의 안내가 여기에 표시돼요.'):tr(locale,'A good conversation starts with hello.','첫 인사로 대화를 시작해 보세요.')}</p>}{conversationMessages.map(message=><div className={'inbox-message '+(message.senderId===inbox?.streamUserId?'mine':'')} key={message.id}><p>{message.text}</p>{message.createdAt&&<small>{new Intl.DateTimeFormat(locale==='ko'?'ko-KR':'en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(message.createdAt))}</small>}</div>)}</div>{selected.kind==='roundy'?<p className="inbox-read-only">{tr(locale,'Roundy Team sends updates here. Replies are not monitored.','Roundy Team의 안내를 받는 곳이에요. 답장은 확인되지 않아요.')}</p>:<form className="inbox-composer" onSubmit={send}><label className="sr-only" htmlFor="inbox-message">{tr(locale,'Message','메시지')}</label><input id="inbox-message" value={draft} onChange={event=>setDraft(event.target.value)} maxLength={MATCH_CHAT_MAX_MESSAGE_LENGTH} placeholder={tr(locale,'Write a message…','메시지 작성…')} disabled={!selected.canSend||sending}/><button className="icon-button" type="submit" disabled={!selected.canSend||sending||!draft.trim()} aria-label={tr(locale,'Send message','메시지 보내기')}><Send size={19}/></button>{sendError&&<p role="alert">{sendError}</p>}</form>}</>}</article></section>;
}
