begin;
-- Additive, backwards-compatible v1 Fact Packs: one time-checked, source-linked fact per record.
alter table public.marketing_trends add column if not exists fact_pack jsonb not null default '{}'::jsonb;
comment on column public.marketing_trends.fact_pack is 'Versioned, bilingual, source-linked factual brief for editorial generation; separate from trend score and paid research.';
with seed(trend_key,expires_at,layout,facts) as (
 values ('2026-creative-seongsu','2026-10-12T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 5~11일","value_en":"October 5–11","source_ids":["S1"]},{"kind":"where","value_ko":"서울 성수동 일대","value_en":"Across Seongsu-dong, Seoul","source_ids":["S1"]},{"kind":"program","value_ko":"전시, 게임, 패션, 음악, 먹거리 등 13개 분야","value_en":"13 categories: exhibitions, games, fashion, music and food","source_ids":["S2"]},{"kind":"experience","value_ko":"동네 여러 장소에 프로그램이 나뉘어 운영","value_en":"Programs are spread across multiple neighborhood venues","source_ids":["S1","S2"]}]'::jsonb),
 ('2026-bitseom-nodeul','2026-10-12T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 2~11일","value_en":"October 2–11","source_ids":["S1"]},{"kind":"where","value_ko":"노들섬","value_en":"Nodeul Island","source_ids":["S1"]},{"kind":"program","value_ko":"레이저 공연과 미디어아트 전시","value_en":"Laser performances and media-art exhibits","source_ids":["S1"]},{"kind":"experience","value_ko":"야간 빛섬축제 프로그램","value_en":"Evening light-art festival programming","source_ids":["S1"]}]'::jsonb),
 ('2026-hangang-drone-oct9','2026-10-10T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 9일 한글날","value_en":"October 9, Hangeul Day","source_ids":["S1"]},{"kind":"where","value_ko":"뚝섬한강공원","value_en":"Ttukseom Hangang Park","source_ids":["S1"]},{"kind":"price","value_ko":"무료 관람 안내","value_en":"Listed as free admission","source_ids":["S1"]},{"kind":"program","value_ko":"야간 드론 라이트 쇼, 시작 시각은 별도 공지 확인","value_en":"Nighttime drone light show; start time must be checked","source_ids":["S1"]}]'::jsonb),
 ('2026-seongsu-popup-wave-oct','2026-10-16T00:00:00+09:00','popup_guide','[{"kind":"when","value_ko":"10월 첫째 주 다양한 팝업, 스위트 에이전트는 10월 2~15일","value_en":"Early October pop-ups; Sweet Agent runs October 2–15","source_ids":["S1","S2"]},{"kind":"where","value_ko":"서울 성수 일대","value_en":"Seongsu neighborhood, Seoul","source_ids":["S1","S2"]},{"kind":"program","value_ko":"캐릭터, 패션, 뷰티, 식품 분야 팝업","value_en":"Character, fashion, beauty and food pop-ups","source_ids":["S1"]},{"kind":"experience","value_ko":"스위트 에이전트 팝업은 체험형 운영 사례","value_en":"Sweet Agent is one experiential pop-up example","source_ids":["S2"]}]'::jsonb),
 ('2026-seoul-bbq-reservation','2026-10-26T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"서울 바비큐 페스티벌 10월 24~25일","value_en":"Seoul BBQ Festival, October 24–25","source_ids":["S2"]},{"kind":"booking","value_ko":"셀프 BBQ존 2차 예약은 10월 6일 오픈 안내","value_en":"Second-round self-BBQ reservations announced for October 6","source_ids":["S1"]},{"kind":"program","value_ko":"셀프 BBQ존 운영","value_en":"Self-service BBQ zone","source_ids":["S1"]},{"kind":"context","value_ko":"참가 방식과 남은 예약 가능 여부는 공식 안내에서 확인","value_en":"Check official booking instructions for remaining slots","source_ids":["S1"]}]'::jsonb),
 ('2026-seoul-hanok-week','2026-10-12T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 2~11일","value_en":"October 2–11","source_ids":["S2"]},{"kind":"where","value_ko":"북촌과 공공한옥 일대","value_en":"Bukchon and public hanok spaces","source_ids":["S1"]},{"kind":"program","value_ko":"서울한옥위크 전통문화 체험 및 프로그램","value_en":"Seoul Hanok Week cultural experiences","source_ids":["S1"]},{"kind":"experience","value_ko":"한옥 공간을 둘러보고 문화 프로그램에 참여","value_en":"Visit hanok sites and join cultural activities","source_ids":["S1"]}]'::jsonb),
 ('curated-2026-seoraeseom-picnic-concert','2026-10-12T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 9~11일, 13:00~19:00","value_en":"October 9–11, 1–7 PM","source_ids":["S2"]},{"kind":"where","value_ko":"반포한강공원 서래섬","value_en":"Seorae Island, Banpo Hangang Park","source_ids":["S2"]},{"kind":"price","value_ko":"공연·쉼터 무료, 일부 식음·체험 유료","value_en":"Free performances and seating; some food and activities cost extra","source_ids":["S2"]},{"kind":"program","value_ko":"라이브 공연, 체험, 피크닉 푸드마켓","value_en":"Live music, hands-on activities and a picnic food market","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-hangang-paper-plane-day','2026-10-11T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 10일, 10:00~18:00","value_en":"October 10, 10 AM–6 PM","source_ids":["S1","S2"]},{"kind":"where","value_ko":"여의도한강공원 녹음수광장","value_en":"Nogeumsu Plaza, Yeouido Hangang Park","source_ids":["S1"]},{"kind":"price","value_ko":"입장 무료","value_en":"Free admission","source_ids":["S2"]},{"kind":"booking","value_ko":"공식 대회 사전접수 마감, 현장 체험·관람 가능","value_en":"Competition registration closed; on-site activities and viewing available","source_ids":["S1"]}]'::jsonb),
 ('curated-2026-autumn-royal-culture-festival','2026-10-12T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 7~11일","value_en":"October 7–11","source_ids":["S1","S2"]},{"kind":"where","value_ko":"경복궁·창덕궁·덕수궁·창경궁·종묘","value_en":"Gyeongbokgung, Changdeokgung, Deoksugung, Changgyeonggung and Jongmyo","source_ids":["S1"]},{"kind":"program","value_ko":"궁궐 공연, 전시, 문화 체험","value_en":"Palace performances, exhibitions and cultural activities","source_ids":["S1","S2"]},{"kind":"booking","value_ko":"일부 프로그램은 사전예약 필요","value_en":"Advance reservations required for selected programs","source_ids":["S2"]}]'::jsonb),
 ('curated-2026-spaf-multiverse','2026-10-26T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 8~25일","value_en":"October 8–25","source_ids":["S1","S2"]},{"kind":"where","value_ko":"국립극장, 대학로 등 서울 공연장","value_en":"National Theater and Daehangno venues","source_ids":["S1"]},{"kind":"program","value_ko":"''예술의 다중우주'' 주제 19개 공연작","value_en":"19 productions under the ''Multiverse of Art'' theme","source_ids":["S2"]},{"kind":"booking","value_ko":"공연별 장소·관람권 정보가 다름","value_en":"Venue and ticket details vary by performance","source_ids":["S1"]}]'::jsonb),
 ('curated-2026-seoul-design-week','2026-10-26T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"서울디자인위크 10월 14~25일, DDP디자인페어 14~18일","value_en":"Seoul Design Week Oct 14–25; DDP Design Fair Oct 14–18","source_ids":["S1","S2"]},{"kind":"where","value_ko":"DDP·성수·연희 등 서울 디자인 공간","value_en":"DDP, Seongsu, Yeonhui and other design sites","source_ids":["S1"]},{"kind":"program","value_ko":"DDP디자인페어와 서울 디자인로드","value_en":"DDP Design Fair and Seoul Design Road","source_ids":["S1"]},{"kind":"experience","value_ko":"서울 전역 디자인 스팟과 라이프스타일 전시","value_en":"Lifestyle exhibitions and design spots around Seoul","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-seoul-silver-grass-festival','2026-10-24T00:00:00+09:00','place_guide','[{"kind":"when","value_ko":"10월 17~23일","value_en":"October 17–23","source_ids":["S1","S2"]},{"kind":"where","value_ko":"월드컵공원 하늘공원","value_en":"Haneul Park, World Cup Park","source_ids":["S1","S2"]},{"kind":"price","value_ko":"무료 입장","value_en":"Free admission","source_ids":["S2"]},{"kind":"program","value_ko":"억새길, 야간 라이트쇼, 버스킹, 자원순환 마켓","value_en":"Silver-grass paths, light show, busking and upcycling market","source_ids":["S1"]}]'::jsonb),
 ('curated-2026-nowon-moonlight-artwalk','2026-11-09T00:00:00+09:00','place_guide','[{"kind":"when","value_ko":"10월 16일~11월 8일, 17:30~22:00","value_en":"October 16–November 8, 5:30–10 PM","source_ids":["S1"]},{"kind":"where","value_ko":"노원 당현천 산책로","value_en":"Danghyeon Stream walking path, Nowon","source_ids":["S1"]},{"kind":"price","value_ko":"무료 관람","value_en":"Free admission","source_ids":["S1"]},{"kind":"program","value_ko":"공공미술 빛조각 설치전, 일부 도슨트 투어 별도 예약","value_en":"Illuminated public art and separately booked docent tours","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-hangang-fall-festival','2026-10-26T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 17~25일","value_en":"October 17–25","source_ids":["S1"]},{"kind":"where","value_ko":"잠원·강서·뚝섬 등 한강공원 7곳","value_en":"Seven Hangang parks including Jamwon, Gangseo and Ttukseom","source_ids":["S1"]},{"kind":"program","value_ko":"운동·요리·음악·휴식 테마 11개 프로그램","value_en":"11 activity, cooking, music and rest programs","source_ids":["S1","S2"]},{"kind":"booking","value_ko":"일부 참여 프로그램은 사전예약 또는 비용 필요","value_en":"Some programs require booking or a participation fee","source_ids":["S2"]}]'::jsonb),
 ('curated-2026-yangjae-autumn-art-salon','2026-10-26T00:00:00+09:00','popup_guide','[{"kind":"when","value_ko":"10월 10~25일 토·일","value_en":"Weekends October 10–25","source_ids":["S1","S2"]},{"kind":"where","value_ko":"양재천길 살롱스트림","value_en":"Salon Stream on Yangjaecheon-gil","source_ids":["S1"]},{"kind":"price","value_ko":"무료 입장, 구매·일부 체험 별도 유료","value_en":"Free entry; purchases and some activities cost extra","source_ids":["S1"]},{"kind":"program","value_ko":"아트마켓, 수공예 체험, 푸드트럭, 버스킹","value_en":"Art market, craft activities, food trucks and busking","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-hongdae-sanrio-stationery','2026-10-12T00:00:00+09:00','popup_guide','[{"kind":"when","value_ko":"10월 2~11일","value_en":"October 2–11","source_ids":["S1","S2"]},{"kind":"where","value_ko":"AK&홍대 2층","value_en":"AK& Hongdae, second floor","source_ids":["S1"]},{"kind":"program","value_ko":"산리오 문구·다이어리 꾸미기 팝업","value_en":"Sanrio stationery and diary-decorating pop-up","source_ids":["S1","S2"]},{"kind":"booking","value_ko":"네이버 사전예약 및 현장예약 방식 안내","value_en":"Naver advance booking and on-site reservation options","source_ids":["S1"]}]'::jsonb),
 ('curated-2026-yeouido-outdoor-book-library','2026-11-01T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"9월 12일~10월 31일 매주 토요일","value_en":"Saturdays, September 12–October 31","source_ids":["S1","S2"]},{"kind":"where","value_ko":"여의도한강공원 멀티플라자","value_en":"Multi Plaza, Yeouido Hangang Park","source_ids":["S1"]},{"kind":"program","value_ko":"10월 17일 재즈, 24일 책 교환, 31일 폐막","value_en":"Jazz Oct 17, book exchange Oct 24, finale Oct 31","source_ids":["S1"]},{"kind":"experience","value_ko":"야외 독서와 공연·체험","value_en":"Outdoor reading, performances and activities","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-mapo-saeujeot-kfood-festival','2026-10-19T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 16~18일","value_en":"October 16–18","source_ids":["S1","S2"]},{"kind":"where","value_ko":"월드컵공원 평화의광장","value_en":"Peace Plaza, World Cup Park","source_ids":["S1"]},{"kind":"price","value_ko":"입장 무료, 먹거리 구매 별도","value_en":"Free entry; food purchases extra","source_ids":["S1"]},{"kind":"program","value_ko":"19m 새우김밥, 보쌈, 재즈·인디 공연","value_en":"19-meter shrimp kimbap, bossam, jazz and indie music","source_ids":["S1","S2"]}]'::jsonb),
 ('curated-2026-hangul-cultural-festival-insadong','2026-10-11T00:00:00+09:00','event_guide','[{"kind":"when","value_ko":"10월 9~10일","value_en":"October 9–10","source_ids":["S1","S2"]},{"kind":"where","value_ko":"인사동 아라아트센터","value_en":"Ara Art Center, Insadong","source_ids":["S1"]},{"kind":"price","value_ko":"무료 행사 안내","value_en":"Listed as a free event","source_ids":["S1"]},{"kind":"program","value_ko":"한글서예 100인전과 전통 문화 체험·공연","value_en":"100-artist Hangeul calligraphy exhibition and cultural activities","source_ids":["S1","S2"]}]'::jsonb)
)
update public.marketing_trends t
set fact_pack=jsonb_build_object(
 'version',1,'origin','curated_from_existing_source_briefs',
 'checked_at',now()::text,'expires_at',seed.expires_at,
 'layout',seed.layout,'facts',seed.facts
),updated_at=now()
from seed
where t.trend_key=seed.trend_key
  and (t.fact_pack is null or t.fact_pack='{}'::jsonb);
commit;
